// Code generated by CHART_VALUES_STRUCT_GENERATOR. DO NOT EDIT.

// This file was autogenerated by the CHART_VALUES_STRUCT_GENERATOR tool on 2024-12-12.
// Any changes will be overwritten.

// These files are generated from the values.yaml files in the k8s/manifests/charts directory.
// Head to the k8s/manifests/charts/Makefile to see how to generate these files.

// Package values contains the Go structs representing the values of the Helm chart.
package values

import (
	"fmt"
	"github.com/mitchellh/mapstructure"
)

type CkLoadbalancerValues_L2 struct {
	Enabled any `mapstructure:"enabled"`
	// interfaces:
	// - "^eth[0-9]+"
	Interfaces []any `mapstructure:"interfaces"`
}

func (v *CkLoadbalancerValues_L2) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type CkLoadbalancerValues_IpPool struct {
	// cidrs:
	// - cidr: "10.42.254.176/28"
	Cidrs []any `mapstructure:"cidrs"`
}

func (v *CkLoadbalancerValues_IpPool) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type CkLoadbalancerValues_Bgp struct {
	Enabled  any `mapstructure:"enabled"`
	LocalAsn any `mapstructure:"localASN"`
	// neighbors:
	// - peerAddress: '10.0.0.60/24'
	// peerASN: 65100
	// peerPort: 179
	Neighbors []any `mapstructure:"neighbors"`
}

func (v *CkLoadbalancerValues_Bgp) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// CkLoadbalancerValues represents the values of the ck-loadbalancer_values.yaml chart
type CkLoadbalancerValues struct {
	Driver any                         `mapstructure:"driver"`
	L2     CkLoadbalancerValues_L2     `mapstructure:"l2"`
	IpPool CkLoadbalancerValues_IpPool `mapstructure:"ipPool"`
	Bgp    CkLoadbalancerValues_Bgp    `mapstructure:"bgp"`
}

func (v *CkLoadbalancerValues) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}
