// Code generated by CHART_VALUES_STRUCT_GENERATOR. DO NOT EDIT.

// This file was autogenerated by the CHART_VALUES_STRUCT_GENERATOR tool on 2024-12-12.
// Any changes will be overwritten.

// These files are generated from the values.yaml files in the k8s/manifests/charts directory.
// Head to the k8s/manifests/charts/Makefile to see how to generate these files.

// Package values contains the Go structs representing the values of the Helm chart.
package values

import (
	"fmt"
	"github.com/mitchellh/mapstructure"
)

type Coredns1360Values_Image struct {
	Repository any `mapstructure:"repository"`
	// Overrides the image tag whose default is the chart appVersion.
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
	// Optionally specify an array of imagePullSecrets.
	// Secrets must be manually created in the namespace.
	// ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
	//
	// pullSecrets:
	// - name: myRegistryKeySecretName
	PullSecrets []any `mapstructure:"pullSecrets"`
}

func (v *Coredns1360Values_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Resources_Limits struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *Coredns1360Values_Resources_Limits) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Resources_Requests struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *Coredns1360Values_Resources_Requests) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Resources struct {
	Limits   Coredns1360Values_Resources_Limits   `mapstructure:"limits"`
	Requests Coredns1360Values_Resources_Requests `mapstructure:"requests"`
}

func (v *Coredns1360Values_Resources) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_RollingUpdate struct {
	MaxUnavailable any `mapstructure:"maxUnavailable"`
	MaxSurge       any `mapstructure:"maxSurge"`
}

func (v *Coredns1360Values_RollingUpdate) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Prometheus_Service_Annotations struct {
	PrometheusIoscrape any `mapstructure:"prometheus.io/scrape"`
	PrometheusIoport   any `mapstructure:"prometheus.io/port"`
}

func (v *Coredns1360Values_Prometheus_Service_Annotations) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Prometheus_Service struct {
	Enabled     any                                              `mapstructure:"enabled"`
	Annotations Coredns1360Values_Prometheus_Service_Annotations `mapstructure:"annotations"`
	Selector    any                                              `mapstructure:"selector"`
}

func (v *Coredns1360Values_Prometheus_Service) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Prometheus_Monitor struct {
	Enabled          any `mapstructure:"enabled"`
	AdditionalLabels any `mapstructure:"additionalLabels"`
	Namespace        any `mapstructure:"namespace"`
	Interval         any `mapstructure:"interval"`
	Selector         any `mapstructure:"selector"`
}

func (v *Coredns1360Values_Prometheus_Monitor) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Prometheus struct {
	Service Coredns1360Values_Prometheus_Service `mapstructure:"service"`
	Monitor Coredns1360Values_Prometheus_Monitor `mapstructure:"monitor"`
}

func (v *Coredns1360Values_Prometheus) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Service struct {
	// clusterIP: ""
	// clusterIPs: []
	// loadBalancerIP: ""
	// loadBalancerClass: ""
	// externalIPs: []
	// externalTrafficPolicy: ""
	// ipFamilyPolicy: ""
	// trafficDistribution: PreferClose
	// The name of the Service
	// If not set, a name is generated using the fullname template
	Name        any `mapstructure:"name"`
	Annotations any `mapstructure:"annotations"`
	// Pod selector
	Selector any `mapstructure:"selector"`
}

func (v *Coredns1360Values_Service) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_ServiceAccount struct {
	Create any `mapstructure:"create"`
	// The name of the ServiceAccount to use
	// If not set and create is true, a name is generated using the fullname template
	Name        any `mapstructure:"name"`
	Annotations any `mapstructure:"annotations"`
}

func (v *Coredns1360Values_ServiceAccount) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Rbac struct {
	// If true, create & use RBAC resources
	Create any `mapstructure:"create"`
	// If true, create and use PodSecurityPolicy
	// The name of the ServiceAccount to use.
	// If not set and create is true, a name is generated using the fullname template
	// name:
	PspEnable any `mapstructure:"pspEnable"`
}

func (v *Coredns1360Values_Rbac) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_SecurityContext_Capabilities struct {
	// - NET_BIND_SERVICE
	Add []any `mapstructure:"add"`
}

func (v *Coredns1360Values_SecurityContext_Capabilities) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Configure SecurityContext for Pod.
// Ensure that required linux capability to bind port number below 1024 is assigned (`CAP_NET_BIND_SERVICE`).
type Coredns1360Values_SecurityContext struct {
	Capabilities Coredns1360Values_SecurityContext_Capabilities `mapstructure:"capabilities"`
}

func (v *Coredns1360Values_SecurityContext) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_ServersItem_ZonesItem struct {
	Zone any `mapstructure:"zone"`
}

func (v *Coredns1360Values_ServersItem_ZonesItem) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// -- expose the service on a different port
// servicePort: 5353
// If serviceType is nodePort you can specify nodePort here
// nodePort: 30053
// hostPort: 53
type Coredns1360Values_ServersItem_PluginsItem struct {
	Name any `mapstructure:"name"`
}

func (v *Coredns1360Values_ServersItem_PluginsItem) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Default zone is what Kubernetes recommends:
// https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
type Coredns1360Values_ServersItem struct {
	Zones []Coredns1360Values_ServersItem_ZonesItem `mapstructure:"zones"`
	Port  any                                       `mapstructure:"port"`
	// -- expose the service on a different port
	// servicePort: 5353
	// If serviceType is nodePort you can specify nodePort here
	// nodePort: 30053
	// hostPort: 53
	Plugins []Coredns1360Values_ServersItem_PluginsItem `mapstructure:"plugins"`
}

func (v *Coredns1360Values_ServersItem) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// To use the livenessProbe, the health plugin needs to be enabled in CoreDNS' server config
type Coredns1360Values_LivenessProbe struct {
	Enabled             any `mapstructure:"enabled"`
	InitialDelaySeconds any `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any `mapstructure:"periodSeconds"`
	TimeoutSeconds      any `mapstructure:"timeoutSeconds"`
	FailureThreshold    any `mapstructure:"failureThreshold"`
	SuccessThreshold    any `mapstructure:"successThreshold"`
}

func (v *Coredns1360Values_LivenessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// To use the readinessProbe, the ready plugin needs to be enabled in CoreDNS' server config
type Coredns1360Values_ReadinessProbe struct {
	Enabled             any `mapstructure:"enabled"`
	InitialDelaySeconds any `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any `mapstructure:"periodSeconds"`
	TimeoutSeconds      any `mapstructure:"timeoutSeconds"`
	FailureThreshold    any `mapstructure:"failureThreshold"`
	SuccessThreshold    any `mapstructure:"successThreshold"`
}

func (v *Coredns1360Values_ReadinessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Alternative configuration for HPA deployment if wanted
// Create HorizontalPodAutoscaler object.
//
// hpa:
// enabled: false
// minReplicas: 1
// maxReplicas: 10
// metrics:
// metrics:
// - type: Resource
// resource:
// name: memory
// target:
// type: Utilization
// averageUtilization: 60
// - type: Resource
// resource:
// name: cpu
// target:
// type: Utilization
// averageUtilization: 60
type Coredns1360Values_Hpa struct {
	Enabled     any   `mapstructure:"enabled"`
	MinReplicas any   `mapstructure:"minReplicas"`
	MaxReplicas any   `mapstructure:"maxReplicas"`
	Metrics     []any `mapstructure:"metrics"`
}

func (v *Coredns1360Values_Hpa) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Optionally specify some extra flags to pass to cluster-proprtional-autoscaler.
// Useful for e.g. the nodelabels flag.
// customFlags:
// - --nodelabels=topology.kubernetes.io/zone=us-east-1a
type Coredns1360Values_Autoscaler_Image struct {
	Repository any `mapstructure:"repository"`
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
	// Optionally specify an array of imagePullSecrets.
	// Secrets must be manually created in the namespace.
	// ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
	//
	// pullSecrets:
	// - name: myRegistryKeySecretName
	PullSecrets []any `mapstructure:"pullSecrets"`
}

func (v *Coredns1360Values_Autoscaler_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Autoscaler_Resources_Requests struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *Coredns1360Values_Autoscaler_Resources_Requests) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Autoscaler_Resources_Limits struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *Coredns1360Values_Autoscaler_Resources_Limits) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// resources for autoscaler pod
type Coredns1360Values_Autoscaler_Resources struct {
	Requests Coredns1360Values_Autoscaler_Resources_Requests `mapstructure:"requests"`
	Limits   Coredns1360Values_Autoscaler_Resources_Limits   `mapstructure:"limits"`
}

func (v *Coredns1360Values_Autoscaler_Resources) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Options for autoscaler configmap
type Coredns1360Values_Autoscaler_Configmap struct {
	// Annotations for the coredns-autoscaler configmap
	// i.e. strategy.spinnaker.io/versioned: "false" to ensure configmap isn't renamed
	Annotations any `mapstructure:"annotations"`
}

func (v *Coredns1360Values_Autoscaler_Configmap) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Enables the livenessProbe for cluster-proportional-autoscaler - this requires version 1.8.0+ of the autoscaler
type Coredns1360Values_Autoscaler_LivenessProbe struct {
	Enabled             any `mapstructure:"enabled"`
	InitialDelaySeconds any `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any `mapstructure:"periodSeconds"`
	TimeoutSeconds      any `mapstructure:"timeoutSeconds"`
	FailureThreshold    any `mapstructure:"failureThreshold"`
	SuccessThreshold    any `mapstructure:"successThreshold"`
}

func (v *Coredns1360Values_Autoscaler_LivenessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Configue a cluster-proportional-autoscaler for coredns
// See https://github.com/kubernetes-incubator/cluster-proportional-autoscaler
type Coredns1360Values_Autoscaler struct {
	// Enabled the cluster-proportional-autoscaler
	Enabled any `mapstructure:"enabled"`
	// Number of cores in the cluster per coredns replica
	CoresPerReplica any `mapstructure:"coresPerReplica"`
	// Number of nodes in the cluster per coredns replica
	NodesPerReplica any `mapstructure:"nodesPerReplica"`
	// Min size of replicaCount
	Min any `mapstructure:"min"`
	// Max size of replicaCount (default of 0 is no max)
	Max any `mapstructure:"max"`
	// Whether to include unschedulable nodes in the nodes/cores calculations - this requires version 1.8.0+ of the autoscaler
	IncludeUnschedulableNodes any `mapstructure:"includeUnschedulableNodes"`
	// If true does not allow single points of failure to form
	PreventSinglePointFailure any `mapstructure:"preventSinglePointFailure"`
	// Annotations for the coredns proportional autoscaler pods
	PodAnnotations any `mapstructure:"podAnnotations"`
	// Optionally specify some extra flags to pass to cluster-proprtional-autoscaler.
	// Useful for e.g. the nodelabels flag.
	// customFlags:
	// - --nodelabels=topology.kubernetes.io/zone=us-east-1a
	//
	Image Coredns1360Values_Autoscaler_Image `mapstructure:"image"`
	// Optional priority class to be used for the autoscaler pods. priorityClassName used if not set.
	PriorityClassName any `mapstructure:"priorityClassName"`
	// expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#affinity-v1-core
	Affinity any `mapstructure:"affinity"`
	// Node labels for pod assignment
	// Ref: https://kubernetes.io/docs/user-guide/node-selection/
	NodeSelector any `mapstructure:"nodeSelector"`
	// expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#toleration-v1-core
	Tolerations []any `mapstructure:"tolerations"`
	// resources for autoscaler pod
	Resources Coredns1360Values_Autoscaler_Resources `mapstructure:"resources"`
	// Options for autoscaler configmap
	Configmap Coredns1360Values_Autoscaler_Configmap `mapstructure:"configmap"`
	// Enables the livenessProbe for cluster-proportional-autoscaler - this requires version 1.8.0+ of the autoscaler
	LivenessProbe Coredns1360Values_Autoscaler_LivenessProbe `mapstructure:"livenessProbe"`
	// optional array of sidecar containers
	// - name: some-container-name
	// image: some-image:latest
	// imagePullPolicy: Always
	ExtraContainers []any `mapstructure:"extraContainers"`
}

func (v *Coredns1360Values_Autoscaler) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Coredns1360Values_Deployment struct {
	SkipConfig any `mapstructure:"skipConfig"`
	Enabled    any `mapstructure:"enabled"`
	Name       any `mapstructure:"name"`
	// Annotations for the coredns deployment
	Annotations any `mapstructure:"annotations"`
	// Pod selector
	Selector any `mapstructure:"selector"`
}

func (v *Coredns1360Values_Deployment) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Coredns1360Values represents the values of the coredns-1.36.0_values.yaml chart
type Coredns1360Values struct {
	Image                         Coredns1360Values_Image         `mapstructure:"image"`
	ReplicaCount                  any                             `mapstructure:"replicaCount"`
	Resources                     Coredns1360Values_Resources     `mapstructure:"resources"`
	RollingUpdate                 Coredns1360Values_RollingUpdate `mapstructure:"rollingUpdate"`
	TerminationGracePeriodSeconds any                             `mapstructure:"terminationGracePeriodSeconds"`
	// cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
	PodAnnotations any                              `mapstructure:"podAnnotations"`
	ServiceType    any                              `mapstructure:"serviceType"`
	Prometheus     Coredns1360Values_Prometheus     `mapstructure:"prometheus"`
	Service        Coredns1360Values_Service        `mapstructure:"service"`
	ServiceAccount Coredns1360Values_ServiceAccount `mapstructure:"serviceAccount"`
	Rbac           Coredns1360Values_Rbac           `mapstructure:"rbac"`
	// isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
	IsClusterService any `mapstructure:"isClusterService"`
	// Optional priority class to be used for the coredns pods. Used for autoscaler if autoscaler.priorityClassName not set.
	PriorityClassName any `mapstructure:"priorityClassName"`
	// Configure the pod level securityContext.
	PodSecurityContext any `mapstructure:"podSecurityContext"`
	// Configure SecurityContext for Pod.
	// Ensure that required linux capability to bind port number below 1024 is assigned (`CAP_NET_BIND_SERVICE`).
	SecurityContext Coredns1360Values_SecurityContext `mapstructure:"securityContext"`
	// Default zone is what Kubernetes recommends:
	// https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
	Servers []Coredns1360Values_ServersItem `mapstructure:"servers"`
	// Complete example with all the options:
	// - zones:                 # the `zones` block can be left out entirely, defaults to "."
	// - zone: hello.world.   # optional, defaults to "."
	// scheme: tls://       # optional, defaults to "" (which equals "dns://" in CoreDNS)
	// - zone: foo.bar.
	// scheme: dns://
	// use_tcp: true        # set this parameter to optionally expose the port on tcp as well as udp for the DNS protocol
	// # Note that this will not work if you are also exposing tls or grpc on the same server
	// port: 12345            # optional, defaults to "" (which equals 53 in CoreDNS)
	// plugins:               # the plugins to use for this server block
	// - name: kubernetes     # name of plugin, if used multiple times ensure that the plugin supports it!
	// parameters: foo bar  # list of parameters after the plugin
	// configBlock: |-      # if the plugin supports extra block style config, supply it here
	// hello world
	// foo bar
	//
	// Extra configuration that is applied outside of the default zone block.
	// Example to include additional config files, which may come from extraVolumes:
	// extraConfig:
	// import:
	// parameters: /opt/coredns/*.conf
	ExtraConfig any `mapstructure:"extraConfig"`
	// To use the livenessProbe, the health plugin needs to be enabled in CoreDNS' server config
	LivenessProbe Coredns1360Values_LivenessProbe `mapstructure:"livenessProbe"`
	// To use the readinessProbe, the ready plugin needs to be enabled in CoreDNS' server config
	ReadinessProbe Coredns1360Values_ReadinessProbe `mapstructure:"readinessProbe"`
	// expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#affinity-v1-core
	// for example:
	// affinity:
	// nodeAffinity:
	// requiredDuringSchedulingIgnoredDuringExecution:
	// nodeSelectorTerms:
	// - matchExpressions:
	// - key: foo.bar.com/role
	// operator: In
	// values:
	// - master
	Affinity any `mapstructure:"affinity"`
	// expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#topologyspreadconstraint-v1-core
	// and supports Helm templating.
	// For example:
	// topologySpreadConstraints:
	// - labelSelector:
	// matchLabels:
	// app.kubernetes.io/name: '{{ template "coredns.name" . }}'
	// app.kubernetes.io/instance: '{{ .Release.Name }}'
	// topologyKey: topology.kubernetes.io/zone
	// maxSkew: 1
	// whenUnsatisfiable: ScheduleAnyway
	// - labelSelector:
	// matchLabels:
	// app.kubernetes.io/name: '{{ template "coredns.name" . }}'
	// app.kubernetes.io/instance: '{{ .Release.Name }}'
	// topologyKey: kubernetes.io/hostname
	// maxSkew: 1
	// whenUnsatisfiable: ScheduleAnyway
	TopologySpreadConstraints []any `mapstructure:"topologySpreadConstraints"`
	// Node labels for pod assignment
	// Ref: https://kubernetes.io/docs/user-guide/node-selection/
	NodeSelector any `mapstructure:"nodeSelector"`
	// expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#toleration-v1-core
	// for example:
	// tolerations:
	// - key: foo.bar.com/role
	// operator: Equal
	// value: master
	// effect: NoSchedule
	Tolerations []any `mapstructure:"tolerations"`
	// https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
	PodDisruptionBudget any `mapstructure:"podDisruptionBudget"`
	// configure custom zone files as per https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/
	// - filename: example.db
	// domain: example.com
	// contents: |
	// example.com.   IN SOA sns.dns.icann.com. noc.dns.icann.com. 2015082541 7200 3600 1209600 3600
	// example.com.   IN NS  b.iana-servers.net.
	// example.com.   IN NS  a.iana-servers.net.
	// example.com.   IN A   192.168.99.102
	// *.example.com. IN A   192.168.99.102
	ZoneFiles []any `mapstructure:"zoneFiles"`
	// optional array of sidecar containers
	ExtraContainers []any `mapstructure:"extraContainers"`
	// - name: some-container-name
	// image: some-image:latest
	// imagePullPolicy: Always
	// optional array of extra volumes to create
	ExtraVolumes []any `mapstructure:"extraVolumes"`
	// - name: some-volume-name
	// emptyDir: {}
	// optional array of mount points for extraVolumes
	// - name: some-volume-name
	// mountPath: /etc/wherever
	ExtraVolumeMounts []any `mapstructure:"extraVolumeMounts"`
	// optional array of secrets to mount inside coredns container
	// possible usecase: need for secure connection with etcd backend
	// - name: etcd-client-certs
	// mountPath: /etc/coredns/tls/etcd
	// defaultMode: 420
	// - name: some-fancy-secret
	// mountPath: /etc/wherever
	// defaultMode: 440
	ExtraSecrets []any `mapstructure:"extraSecrets"`
	// optional array of environment variables for coredns container
	// possible usecase: provides username and password for etcd user authentications
	// - name: WHATEVER_ENV
	// value: whatever
	// - name: SOME_SECRET_ENV
	// valueFrom:
	// secretKeyRef:
	// name: some-secret-name
	// key: secret-key
	Env []any `mapstructure:"env"`
	// To support legacy deployments using CoreDNS with the "k8s-app: kube-dns" label selectors.
	// See https://github.com/coredns/helm/blob/master/charts/coredns/README.md#adopting-existing-coredns-resources
	// k8sAppLabelOverride: "kube-dns"
	//
	// Custom labels to apply to Deployment, Pod, Configmap, Service, ServiceMonitor. Including autoscaler if enabled.
	CustomLabels any `mapstructure:"customLabels"`
	// Custom annotations to apply to Deployment, Pod, Configmap, Service, ServiceMonitor. Including autoscaler if enabled.
	CustomAnnotations any `mapstructure:"customAnnotations"`
	// Alternative configuration for HPA deployment if wanted
	// Create HorizontalPodAutoscaler object.
	//
	// hpa:
	// enabled: false
	// minReplicas: 1
	// maxReplicas: 10
	// metrics:
	// metrics:
	// - type: Resource
	// resource:
	// name: memory
	// target:
	// type: Utilization
	// averageUtilization: 60
	// - type: Resource
	// resource:
	// name: cpu
	// target:
	// type: Utilization
	// averageUtilization: 60
	//
	Hpa Coredns1360Values_Hpa `mapstructure:"hpa"`
	// Configue a cluster-proportional-autoscaler for coredns
	// See https://github.com/kubernetes-incubator/cluster-proportional-autoscaler
	Autoscaler Coredns1360Values_Autoscaler `mapstructure:"autoscaler"`
	Deployment Coredns1360Values_Deployment `mapstructure:"deployment"`
}

func (v *Coredns1360Values) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}
