// Code generated by CHART_VALUES_STRUCT_GENERATOR. DO NOT EDIT.

// This file was autogenerated by the CHART_VALUES_STRUCT_GENERATOR tool on 2024-12-12.
// Any changes will be overwritten.

// These files are generated from the values.yaml files in the k8s/manifests/charts directory.
// Head to the k8s/manifests/charts/Makefile to see how to generate these files.

// Package values contains the Go structs representing the values of the Helm chart.
package values

import (
	"fmt"
	"github.com/mitchellh/mapstructure"
)

// To configure MetalLB, you must specify ONE of the following two
// options.
type Metallb0148Values_Rbac struct {
	// create specifies whether to install and use RBAC rules.
	Create any `mapstructure:"create"`
}

func (v *Metallb0148Values_Rbac) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// the image to be used for the kuberbacproxy container
type Metallb0148Values_Prometheus_RbacProxy struct {
	Repository any `mapstructure:"repository"`
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
}

func (v *Metallb0148Values_Prometheus_RbacProxy) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Prometheus Operator PodMonitors
type Metallb0148Values_Prometheus_PodMonitor struct {
	// enable support for Prometheus Operator
	Enabled any `mapstructure:"enabled"`
	// optional additionnal labels for podMonitors
	AdditionalLabels any `mapstructure:"additionalLabels"`
	// optional annotations for podMonitors
	Annotations any `mapstructure:"annotations"`
	// Job label for scrape target
	JobLabel any `mapstructure:"jobLabel"`
	// Scrape interval. If not set, the Prometheus default scrape interval is used.
	Interval any `mapstructure:"interval"`
	// metric relabel configs to apply to samples before ingestion.
	// - action: keep
	// regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
	// sourceLabels: [__name__]
	MetricRelabelings []any `mapstructure:"metricRelabelings"`
	// relabel configs to apply to samples before ingestion.
	// - sourceLabels: [__meta_kubernetes_pod_node_name]
	// separator: ;
	// regex: ^(.*)$
	// target_label: nodename
	// replacement: $1
	// action: replace
	Relabelings []any `mapstructure:"relabelings"`
}

func (v *Metallb0148Values_Prometheus_PodMonitor) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// optional tls configuration for the speaker serviceMonitor, in case
// secure metrics are enabled.
type Metallb0148Values_Prometheus_ServiceMonitor_Speaker_TlsConfig struct {
	InsecureSkipVerify any `mapstructure:"insecureSkipVerify"`
}

func (v *Metallb0148Values_Prometheus_ServiceMonitor_Speaker_TlsConfig) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_ServiceMonitor_Speaker struct {
	// optional additional labels for the speaker serviceMonitor
	AdditionalLabels any `mapstructure:"additionalLabels"`
	// optional additional annotations for the speaker serviceMonitor
	Annotations any `mapstructure:"annotations"`
	// optional tls configuration for the speaker serviceMonitor, in case
	// secure metrics are enabled.
	TlsConfig Metallb0148Values_Prometheus_ServiceMonitor_Speaker_TlsConfig `mapstructure:"tlsConfig"`
}

func (v *Metallb0148Values_Prometheus_ServiceMonitor_Speaker) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// optional tls configuration for the controller serviceMonitor, in case
// secure metrics are enabled.
type Metallb0148Values_Prometheus_ServiceMonitor_Controller_TlsConfig struct {
	InsecureSkipVerify any `mapstructure:"insecureSkipVerify"`
}

func (v *Metallb0148Values_Prometheus_ServiceMonitor_Controller_TlsConfig) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_ServiceMonitor_Controller struct {
	// optional additional labels for the controller serviceMonitor
	AdditionalLabels any `mapstructure:"additionalLabels"`
	// optional additional annotations for the controller serviceMonitor
	Annotations any `mapstructure:"annotations"`
	// optional tls configuration for the controller serviceMonitor, in case
	// secure metrics are enabled.
	TlsConfig Metallb0148Values_Prometheus_ServiceMonitor_Controller_TlsConfig `mapstructure:"tlsConfig"`
}

func (v *Metallb0148Values_Prometheus_ServiceMonitor_Controller) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Prometheus Operator ServiceMonitors. To be used as an alternative
// to podMonitor, supports secure metrics.
type Metallb0148Values_Prometheus_ServiceMonitor struct {
	// enable support for Prometheus Operator
	Enabled    any                                                    `mapstructure:"enabled"`
	Speaker    Metallb0148Values_Prometheus_ServiceMonitor_Speaker    `mapstructure:"speaker"`
	Controller Metallb0148Values_Prometheus_ServiceMonitor_Controller `mapstructure:"controller"`
	// Job label for scrape target
	JobLabel any `mapstructure:"jobLabel"`
	// Scrape interval. If not set, the Prometheus default scrape interval is used.
	Interval any `mapstructure:"interval"`
	// metric relabel configs to apply to samples before ingestion.
	// - action: keep
	// regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
	// sourceLabels: [__name__]
	MetricRelabelings []any `mapstructure:"metricRelabelings"`
	// relabel configs to apply to samples before ingestion.
	// - sourceLabels: [__meta_kubernetes_pod_node_name]
	// separator: ;
	// regex: ^(.*)$
	// target_label: nodename
	// replacement: $1
	// action: replace
	Relabelings []any `mapstructure:"relabelings"`
}

func (v *Metallb0148Values_Prometheus_ServiceMonitor) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_PrometheusRule_StaleConfig_Labels struct {
	Severity any `mapstructure:"severity"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_StaleConfig_Labels) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// MetalLBStaleConfig
type Metallb0148Values_Prometheus_PrometheusRule_StaleConfig struct {
	Enabled any                                                            `mapstructure:"enabled"`
	Labels  Metallb0148Values_Prometheus_PrometheusRule_StaleConfig_Labels `mapstructure:"labels"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_StaleConfig) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_PrometheusRule_ConfigNotLoaded_Labels struct {
	Severity any `mapstructure:"severity"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_ConfigNotLoaded_Labels) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// MetalLBConfigNotLoaded
type Metallb0148Values_Prometheus_PrometheusRule_ConfigNotLoaded struct {
	Enabled any                                                                `mapstructure:"enabled"`
	Labels  Metallb0148Values_Prometheus_PrometheusRule_ConfigNotLoaded_Labels `mapstructure:"labels"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_ConfigNotLoaded) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_PrometheusRule_AddressPoolExhausted_Labels struct {
	Severity any `mapstructure:"severity"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_AddressPoolExhausted_Labels) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// MetalLBAddressPoolExhausted
type Metallb0148Values_Prometheus_PrometheusRule_AddressPoolExhausted struct {
	Enabled any                                                                     `mapstructure:"enabled"`
	Labels  Metallb0148Values_Prometheus_PrometheusRule_AddressPoolExhausted_Labels `mapstructure:"labels"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_AddressPoolExhausted) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage_ThresholdsItem_Labels struct {
	Severity any `mapstructure:"severity"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage_ThresholdsItem_Labels) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage_ThresholdsItem struct {
	Percent any                                                                                `mapstructure:"percent"`
	Labels  Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage_ThresholdsItem_Labels `mapstructure:"labels"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage_ThresholdsItem) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage struct {
	Enabled    any                                                                           `mapstructure:"enabled"`
	Thresholds []Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage_ThresholdsItem `mapstructure:"thresholds"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus_PrometheusRule_BgpSessionDown_Labels struct {
	Severity any `mapstructure:"severity"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_BgpSessionDown_Labels) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// MetalLBBGPSessionDown
type Metallb0148Values_Prometheus_PrometheusRule_BgpSessionDown struct {
	Enabled any                                                               `mapstructure:"enabled"`
	Labels  Metallb0148Values_Prometheus_PrometheusRule_BgpSessionDown_Labels `mapstructure:"labels"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule_BgpSessionDown) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Prometheus Operator alertmanager alerts
type Metallb0148Values_Prometheus_PrometheusRule struct {
	// enable alertmanager alerts
	Enabled any `mapstructure:"enabled"`
	// optional additionnal labels for prometheusRules
	AdditionalLabels any `mapstructure:"additionalLabels"`
	// optional annotations for prometheusRules
	Annotations any `mapstructure:"annotations"`
	// MetalLBStaleConfig
	StaleConfig Metallb0148Values_Prometheus_PrometheusRule_StaleConfig `mapstructure:"staleConfig"`
	// MetalLBConfigNotLoaded
	ConfigNotLoaded Metallb0148Values_Prometheus_PrometheusRule_ConfigNotLoaded `mapstructure:"configNotLoaded"`
	// MetalLBAddressPoolExhausted
	AddressPoolExhausted Metallb0148Values_Prometheus_PrometheusRule_AddressPoolExhausted `mapstructure:"addressPoolExhausted"`
	AddressPoolUsage     Metallb0148Values_Prometheus_PrometheusRule_AddressPoolUsage     `mapstructure:"addressPoolUsage"`
	// MetalLBBGPSessionDown
	BgpSessionDown Metallb0148Values_Prometheus_PrometheusRule_BgpSessionDown `mapstructure:"bgpSessionDown"`
	ExtraAlerts    []any                                                      `mapstructure:"extraAlerts"`
}

func (v *Metallb0148Values_Prometheus_PrometheusRule) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Prometheus struct {
	// scrape annotations specifies whether to add Prometheus metric
	// auto-collection annotations to pods. See
	// https://github.com/prometheus/prometheus/blob/release-2.1/documentation/examples/prometheus-kubernetes.yml
	// for a corresponding Prometheus configuration. Alternatively, you
	// may want to use the Prometheus Operator
	// (https://github.com/coreos/prometheus-operator) for more powerful
	// monitoring configuration. If you use the Prometheus operator, this
	// can be left at false.
	ScrapeAnnotations any `mapstructure:"scrapeAnnotations"`
	// port both controller and speaker will listen on for metrics
	MetricsPort any `mapstructure:"metricsPort"`
	// if set, enables rbac proxy on the controller and speaker to expose
	// the metrics via tls.
	// secureMetricsPort: 9120
	//
	// the name of the secret to be mounted in the speaker pod
	// to expose the metrics securely. If not present, a self signed
	// certificate to be used.
	SpeakerMetricsTlssecret any `mapstructure:"speakerMetricsTLSSecret"`
	// the name of the secret to be mounted in the controller pod
	// to expose the metrics securely. If not present, a self signed
	// certificate to be used.
	ControllerMetricsTlssecret any `mapstructure:"controllerMetricsTLSSecret"`
	// prometheus doens't have the permission to scrape all namespaces so we give it permission to scrape metallb's one
	RbacPrometheus any `mapstructure:"rbacPrometheus"`
	// the service account used by prometheus
	// required when " .Values.prometheus.rbacPrometheus == true " and " .Values.prometheus.podMonitor.enabled=true or prometheus.serviceMonitor.enabled=true "
	ServiceAccount any `mapstructure:"serviceAccount"`
	// the namespace where prometheus is deployed
	// required when " .Values.prometheus.rbacPrometheus == true " and " .Values.prometheus.podMonitor.enabled=true or prometheus.serviceMonitor.enabled=true "
	Namespace any `mapstructure:"namespace"`
	// the image to be used for the kuberbacproxy container
	RbacProxy Metallb0148Values_Prometheus_RbacProxy `mapstructure:"rbacProxy"`
	// Prometheus Operator PodMonitors
	PodMonitor Metallb0148Values_Prometheus_PodMonitor `mapstructure:"podMonitor"`
	// Prometheus Operator ServiceMonitors. To be used as an alternative
	// to podMonitor, supports secure metrics.
	ServiceMonitor Metallb0148Values_Prometheus_ServiceMonitor `mapstructure:"serviceMonitor"`
	// Prometheus Operator alertmanager alerts
	PrometheusRule Metallb0148Values_Prometheus_PrometheusRule `mapstructure:"prometheusRule"`
}

func (v *Metallb0148Values_Prometheus) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// command: /controller
// webhookMode: enabled
type Metallb0148Values_Controller_Image struct {
	Repository any `mapstructure:"repository"`
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
}

func (v *Metallb0148Values_Controller_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// @param controller.updateStrategy.type Metallb controller deployment strategy type.
// ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
// e.g:
// strategy:
// type: RollingUpdate
// rollingUpdate:
// maxSurge: 25%
// maxUnavailable: 25%
type Metallb0148Values_Controller_Strategy struct {
	Type any `mapstructure:"type"`
}

func (v *Metallb0148Values_Controller_Strategy) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Controller_ServiceAccount struct {
	// Specifies whether a ServiceAccount should be created
	Create any `mapstructure:"create"`
	// The name of the ServiceAccount to use. If not set and create is
	// true, a name is generated using the fullname template
	Name        any `mapstructure:"name"`
	Annotations any `mapstructure:"annotations"`
}

func (v *Metallb0148Values_Controller_ServiceAccount) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Controller_SecurityContext struct {
	RunAsNonRoot any `mapstructure:"runAsNonRoot"`
	// nobody
	RunAsUser any `mapstructure:"runAsUser"`
	FsGroup   any `mapstructure:"fsGroup"`
}

func (v *Metallb0148Values_Controller_SecurityContext) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Controller_LivenessProbe struct {
	Enabled             any `mapstructure:"enabled"`
	FailureThreshold    any `mapstructure:"failureThreshold"`
	InitialDelaySeconds any `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any `mapstructure:"periodSeconds"`
	SuccessThreshold    any `mapstructure:"successThreshold"`
	TimeoutSeconds      any `mapstructure:"timeoutSeconds"`
}

func (v *Metallb0148Values_Controller_LivenessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Controller_ReadinessProbe struct {
	Enabled             any `mapstructure:"enabled"`
	FailureThreshold    any `mapstructure:"failureThreshold"`
	InitialDelaySeconds any `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any `mapstructure:"periodSeconds"`
	SuccessThreshold    any `mapstructure:"successThreshold"`
	TimeoutSeconds      any `mapstructure:"timeoutSeconds"`
}

func (v *Metallb0148Values_Controller_ReadinessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// controller contains configuration specific to the MetalLB cluster
// controller.
type Metallb0148Values_Controller struct {
	Enabled any `mapstructure:"enabled"`
	// -- Controller log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
	LogLevel any `mapstructure:"logLevel"`
	// command: /controller
	// webhookMode: enabled
	Image Metallb0148Values_Controller_Image `mapstructure:"image"`
	// @param controller.updateStrategy.type Metallb controller deployment strategy type.
	// ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
	// e.g:
	// strategy:
	// type: RollingUpdate
	// rollingUpdate:
	// maxSurge: 25%
	// maxUnavailable: 25%
	//
	Strategy        Metallb0148Values_Controller_Strategy        `mapstructure:"strategy"`
	ServiceAccount  Metallb0148Values_Controller_ServiceAccount  `mapstructure:"serviceAccount"`
	SecurityContext Metallb0148Values_Controller_SecurityContext `mapstructure:"securityContext"`
	Resources       any                                          `mapstructure:"resources"`
	// limits:
	// cpu: 100m
	// memory: 100Mi
	NodeSelector      any                                         `mapstructure:"nodeSelector"`
	Tolerations       []any                                       `mapstructure:"tolerations"`
	PriorityClassName any                                         `mapstructure:"priorityClassName"`
	RuntimeClassName  any                                         `mapstructure:"runtimeClassName"`
	Affinity          any                                         `mapstructure:"affinity"`
	PodAnnotations    any                                         `mapstructure:"podAnnotations"`
	Labels            any                                         `mapstructure:"labels"`
	LivenessProbe     Metallb0148Values_Controller_LivenessProbe  `mapstructure:"livenessProbe"`
	ReadinessProbe    Metallb0148Values_Controller_ReadinessProbe `mapstructure:"readinessProbe"`
	TlsMinVersion     any                                         `mapstructure:"tlsMinVersion"`
	TlsCipherSuites   any                                         `mapstructure:"tlsCipherSuites"`
	ExtraContainers   []any                                       `mapstructure:"extraContainers"`
}

func (v *Metallb0148Values_Controller) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_Memberlist struct {
	Enabled            any `mapstructure:"enabled"`
	MlBindPort         any `mapstructure:"mlBindPort"`
	MlBindAddrOverride any `mapstructure:"mlBindAddrOverride"`
	MlSecretKeyPath    any `mapstructure:"mlSecretKeyPath"`
}

func (v *Metallb0148Values_Speaker_Memberlist) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_ExcludeInterfaces struct {
	Enabled any `mapstructure:"enabled"`
}

func (v *Metallb0148Values_Speaker_ExcludeInterfaces) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_Image struct {
	Repository any `mapstructure:"repository"`
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
}

func (v *Metallb0148Values_Speaker_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// @param speaker.updateStrategy.type Speaker daemonset strategy type
// ref: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/
type Metallb0148Values_Speaker_UpdateStrategy struct {
	// StrategyType
	// Can be set to RollingUpdate or OnDelete
	//
	Type any `mapstructure:"type"`
}

func (v *Metallb0148Values_Speaker_UpdateStrategy) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_ServiceAccount struct {
	// Specifies whether a ServiceAccount should be created
	Create any `mapstructure:"create"`
	// The name of the ServiceAccount to use. If not set and create is
	// true, a name is generated using the fullname template
	Name        any `mapstructure:"name"`
	Annotations any `mapstructure:"annotations"`
}

func (v *Metallb0148Values_Speaker_ServiceAccount) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_LivenessProbe struct {
	Enabled             any `mapstructure:"enabled"`
	FailureThreshold    any `mapstructure:"failureThreshold"`
	InitialDelaySeconds any `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any `mapstructure:"periodSeconds"`
	SuccessThreshold    any `mapstructure:"successThreshold"`
	TimeoutSeconds      any `mapstructure:"timeoutSeconds"`
}

func (v *Metallb0148Values_Speaker_LivenessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_ReadinessProbe struct {
	Enabled             any `mapstructure:"enabled"`
	FailureThreshold    any `mapstructure:"failureThreshold"`
	InitialDelaySeconds any `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any `mapstructure:"periodSeconds"`
	SuccessThreshold    any `mapstructure:"successThreshold"`
	TimeoutSeconds      any `mapstructure:"timeoutSeconds"`
}

func (v *Metallb0148Values_Speaker_ReadinessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_StartupProbe struct {
	Enabled          any `mapstructure:"enabled"`
	FailureThreshold any `mapstructure:"failureThreshold"`
	PeriodSeconds    any `mapstructure:"periodSeconds"`
}

func (v *Metallb0148Values_Speaker_StartupProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_Frr_Image struct {
	Repository any `mapstructure:"repository"`
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
}

func (v *Metallb0148Values_Speaker_Frr_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// frr contains configuration specific to the MetalLB FRR container,
// for speaker running alongside FRR.
type Metallb0148Values_Speaker_Frr struct {
	Enabled     any                                 `mapstructure:"enabled"`
	Image       Metallb0148Values_Speaker_Frr_Image `mapstructure:"image"`
	MetricsPort any                                 `mapstructure:"metricsPort"`
	// if set, enables a rbac proxy sidecar container on the speaker to
	// expose the frr metrics via tls.
	// secureMetricsPort: 9121
	//
	Resources any `mapstructure:"resources"`
}

func (v *Metallb0148Values_Speaker_Frr) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_Reloader struct {
	Resources any `mapstructure:"resources"`
}

func (v *Metallb0148Values_Speaker_Reloader) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Speaker_FrrMetrics struct {
	Resources any `mapstructure:"resources"`
}

func (v *Metallb0148Values_Speaker_FrrMetrics) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// speaker contains configuration specific to the MetalLB speaker
// daemonset.
type Metallb0148Values_Speaker struct {
	Enabled any `mapstructure:"enabled"`
	// command: /speaker
	// -- Speaker log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
	LogLevel          any                                         `mapstructure:"logLevel"`
	TolerateMaster    any                                         `mapstructure:"tolerateMaster"`
	Memberlist        Metallb0148Values_Speaker_Memberlist        `mapstructure:"memberlist"`
	ExcludeInterfaces Metallb0148Values_Speaker_ExcludeInterfaces `mapstructure:"excludeInterfaces"`
	// ignore the exclude-from-external-loadbalancer label
	IgnoreExcludeLb any                             `mapstructure:"ignoreExcludeLB"`
	Image           Metallb0148Values_Speaker_Image `mapstructure:"image"`
	// @param speaker.updateStrategy.type Speaker daemonset strategy type
	// ref: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/
	//
	UpdateStrategy  Metallb0148Values_Speaker_UpdateStrategy `mapstructure:"updateStrategy"`
	ServiceAccount  Metallb0148Values_Speaker_ServiceAccount `mapstructure:"serviceAccount"`
	SecurityContext any                                      `mapstructure:"securityContext"`
	// Defines a secret name for the controller to generate a memberlist encryption secret
	// By default secretName: {{ "metallb.fullname" }}-memberlist
	//
	// secretName:
	Resources any `mapstructure:"resources"`
	// limits:
	// cpu: 100m
	// memory: 100Mi
	NodeSelector      any   `mapstructure:"nodeSelector"`
	Tolerations       []any `mapstructure:"tolerations"`
	PriorityClassName any   `mapstructure:"priorityClassName"`
	Affinity          any   `mapstructure:"affinity"`
	// Selects which runtime class will be used by the pod.
	RuntimeClassName any                                      `mapstructure:"runtimeClassName"`
	PodAnnotations   any                                      `mapstructure:"podAnnotations"`
	Labels           any                                      `mapstructure:"labels"`
	LivenessProbe    Metallb0148Values_Speaker_LivenessProbe  `mapstructure:"livenessProbe"`
	ReadinessProbe   Metallb0148Values_Speaker_ReadinessProbe `mapstructure:"readinessProbe"`
	StartupProbe     Metallb0148Values_Speaker_StartupProbe   `mapstructure:"startupProbe"`
	// frr contains configuration specific to the MetalLB FRR container,
	// for speaker running alongside FRR.
	Frr             Metallb0148Values_Speaker_Frr        `mapstructure:"frr"`
	Reloader        Metallb0148Values_Speaker_Reloader   `mapstructure:"reloader"`
	FrrMetrics      Metallb0148Values_Speaker_FrrMetrics `mapstructure:"frrMetrics"`
	ExtraContainers []any                                `mapstructure:"extraContainers"`
}

func (v *Metallb0148Values_Speaker) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type Metallb0148Values_Crds struct {
	Enabled                 any `mapstructure:"enabled"`
	ValidationFailurePolicy any `mapstructure:"validationFailurePolicy"`
}

func (v *Metallb0148Values_Crds) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// frrk8s contains the configuration related to using an frrk8s instance
// (github.com/metallb/frr-k8s) as the backend for the BGP implementation.
// This allows configuring additional frr parameters in combination to those
// applied by MetalLB.
type Metallb0148Values_Frrk8S struct {
	// if set, enables frrk8s as a backend. This is mutually exclusive to frr
	// mode.
	Enabled   any `mapstructure:"enabled"`
	External  any `mapstructure:"external"`
	Namespace any `mapstructure:"namespace"`
}

func (v *Metallb0148Values_Frrk8S) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// Metallb0148Values represents the values of the metallb-0.14.8_values.yaml chart
type Metallb0148Values struct {
	ImagePullSecrets  []any `mapstructure:"imagePullSecrets"`
	NameOverride      any   `mapstructure:"nameOverride"`
	FullnameOverride  any   `mapstructure:"fullnameOverride"`
	LoadBalancerClass any   `mapstructure:"loadBalancerClass"`
	// To configure MetalLB, you must specify ONE of the following two
	// options.
	//
	Rbac       Metallb0148Values_Rbac       `mapstructure:"rbac"`
	Prometheus Metallb0148Values_Prometheus `mapstructure:"prometheus"`
	// controller contains configuration specific to the MetalLB cluster
	// controller.
	Controller Metallb0148Values_Controller `mapstructure:"controller"`
	// speaker contains configuration specific to the MetalLB speaker
	// daemonset.
	Speaker Metallb0148Values_Speaker `mapstructure:"speaker"`
	Crds    Metallb0148Values_Crds    `mapstructure:"crds"`
	// frrk8s contains the configuration related to using an frrk8s instance
	// (github.com/metallb/frr-k8s) as the backend for the BGP implementation.
	// This allows configuring additional frr parameters in combination to those
	// applied by MetalLB.
	Frrk8S Metallb0148Values_Frrk8S `mapstructure:"frrk8s"`
}

func (v *Metallb0148Values) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}
