// Code generated by CHART_VALUES_STRUCT_GENERATOR. DO NOT EDIT.

// This file was autogenerated by the CHART_VALUES_STRUCT_GENERATOR tool on 2024-12-12.
// Any changes will be overwritten.

// These files are generated from the values.yaml files in the k8s/manifests/charts directory.
// Head to the k8s/manifests/charts/Makefile to see how to generate these files.

// Package values contains the Go structs representing the values of the Helm chart.
package values

import (
	"fmt"
	"github.com/mitchellh/mapstructure"
)

type MetricsServer3122Values_Image struct {
	Repository any `mapstructure:"repository"`
	// Overrides the image tag whose default is v{{ .Chart.AppVersion }}
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
}

func (v *MetricsServer3122Values_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_ServiceAccount struct {
	// Specifies whether a service account should be created
	Create any `mapstructure:"create"`
	// Annotations to add to the service account
	Annotations any `mapstructure:"annotations"`
	// The name of the service account to use.
	// If not set and create is true, a name is generated using the fullname template
	Name any `mapstructure:"name"`
	// The list of secrets mountable by this service account.
	// See https://kubernetes.io/docs/reference/labels-annotations-taints/#enforce-mountable-secrets
	Secrets []any `mapstructure:"secrets"`
}

func (v *MetricsServer3122Values_ServiceAccount) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_Rbac struct {
	// Specifies whether RBAC resources should be created
	Create any `mapstructure:"create"`
	// Note: PodSecurityPolicy will not be created when Kubernetes version is 1.25 or later.
	PspEnabled any `mapstructure:"pspEnabled"`
}

func (v *MetricsServer3122Values_Rbac) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_ApiService struct {
	// Specifies if the v1beta1.metrics.k8s.io API service should be created.
	//
	// You typically want this enabled! If you disable API service creation you have to
	// manage it outside of this chart for e.g horizontal pod autoscaling to
	// work with this release.
	Create any `mapstructure:"create"`
	// Annotations to add to the API service
	Annotations any `mapstructure:"annotations"`
	// Specifies whether to skip TLS verification
	InsecureSkipTlsverify any `mapstructure:"insecureSkipTLSVerify"`
	// The PEM encoded CA bundle for TLS verification
	CaBundle any `mapstructure:"caBundle"`
}

func (v *MetricsServer3122Values_ApiService) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_SecurityContext_SeccompProfile struct {
	Type any `mapstructure:"type"`
}

func (v *MetricsServer3122Values_SecurityContext_SeccompProfile) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_SecurityContext_Capabilities struct {
	// - ALL
	Drop []any `mapstructure:"drop"`
}

func (v *MetricsServer3122Values_SecurityContext_Capabilities) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_SecurityContext struct {
	AllowPrivilegeEscalation any                                                    `mapstructure:"allowPrivilegeEscalation"`
	ReadOnlyRootFilesystem   any                                                    `mapstructure:"readOnlyRootFilesystem"`
	RunAsNonRoot             any                                                    `mapstructure:"runAsNonRoot"`
	RunAsUser                any                                                    `mapstructure:"runAsUser"`
	SeccompProfile           MetricsServer3122Values_SecurityContext_SeccompProfile `mapstructure:"seccompProfile"`
	Capabilities             MetricsServer3122Values_SecurityContext_Capabilities   `mapstructure:"capabilities"`
}

func (v *MetricsServer3122Values_SecurityContext) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_HostNetwork struct {
	// Specifies if metrics-server should be started in hostNetwork mode.
	//
	// You would require this enabled if you use alternate overlay networking for pods and
	// API server unable to communicate with metrics-server. As an example, this is required
	// if you use Weave network on EKS
	Enabled any `mapstructure:"enabled"`
}

func (v *MetricsServer3122Values_HostNetwork) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_PodDisruptionBudget struct {
	// https://kubernetes.io/docs/tasks/run-application/configure-pdb/
	Enabled        any `mapstructure:"enabled"`
	MinAvailable   any `mapstructure:"minAvailable"`
	MaxUnavailable any `mapstructure:"maxUnavailable"`
}

func (v *MetricsServer3122Values_PodDisruptionBudget) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_LivenessProbe_HttpGet struct {
	Path   any `mapstructure:"path"`
	Port   any `mapstructure:"port"`
	Scheme any `mapstructure:"scheme"`
}

func (v *MetricsServer3122Values_LivenessProbe_HttpGet) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_LivenessProbe struct {
	HttpGet             MetricsServer3122Values_LivenessProbe_HttpGet `mapstructure:"httpGet"`
	InitialDelaySeconds any                                           `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any                                           `mapstructure:"periodSeconds"`
	FailureThreshold    any                                           `mapstructure:"failureThreshold"`
}

func (v *MetricsServer3122Values_LivenessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_ReadinessProbe_HttpGet struct {
	Path   any `mapstructure:"path"`
	Port   any `mapstructure:"port"`
	Scheme any `mapstructure:"scheme"`
}

func (v *MetricsServer3122Values_ReadinessProbe_HttpGet) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_ReadinessProbe struct {
	HttpGet             MetricsServer3122Values_ReadinessProbe_HttpGet `mapstructure:"httpGet"`
	InitialDelaySeconds any                                            `mapstructure:"initialDelaySeconds"`
	PeriodSeconds       any                                            `mapstructure:"periodSeconds"`
	FailureThreshold    any                                            `mapstructure:"failureThreshold"`
}

func (v *MetricsServer3122Values_ReadinessProbe) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_Service struct {
	Type        any `mapstructure:"type"`
	Port        any `mapstructure:"port"`
	Annotations any `mapstructure:"annotations"`
	// Add these labels to have metrics-server show up in `kubectl cluster-info`
	// kubernetes.io/cluster-service: "true"
	// kubernetes.io/name: "Metrics-server"
	Labels any `mapstructure:"labels"`
}

func (v *MetricsServer3122Values_Service) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_Image struct {
	Repository any `mapstructure:"repository"`
	Tag        any `mapstructure:"tag"`
}

func (v *MetricsServer3122Values_AddonResizer_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_SecurityContext_SeccompProfile struct {
	Type any `mapstructure:"type"`
}

func (v *MetricsServer3122Values_AddonResizer_SecurityContext_SeccompProfile) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_SecurityContext_Capabilities struct {
	// - ALL
	Drop []any `mapstructure:"drop"`
}

func (v *MetricsServer3122Values_AddonResizer_SecurityContext_Capabilities) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_SecurityContext struct {
	AllowPrivilegeEscalation any                                                                 `mapstructure:"allowPrivilegeEscalation"`
	ReadOnlyRootFilesystem   any                                                                 `mapstructure:"readOnlyRootFilesystem"`
	RunAsNonRoot             any                                                                 `mapstructure:"runAsNonRoot"`
	RunAsUser                any                                                                 `mapstructure:"runAsUser"`
	SeccompProfile           MetricsServer3122Values_AddonResizer_SecurityContext_SeccompProfile `mapstructure:"seccompProfile"`
	Capabilities             MetricsServer3122Values_AddonResizer_SecurityContext_Capabilities   `mapstructure:"capabilities"`
}

func (v *MetricsServer3122Values_AddonResizer_SecurityContext) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_Resources_Requests struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *MetricsServer3122Values_AddonResizer_Resources_Requests) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_Resources_Limits struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *MetricsServer3122Values_AddonResizer_Resources_Limits) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_Resources struct {
	Requests MetricsServer3122Values_AddonResizer_Resources_Requests `mapstructure:"requests"`
	Limits   MetricsServer3122Values_AddonResizer_Resources_Limits   `mapstructure:"limits"`
}

func (v *MetricsServer3122Values_AddonResizer_Resources) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer_Nanny struct {
	Cpu            any `mapstructure:"cpu"`
	ExtraCpu       any `mapstructure:"extraCpu"`
	Memory         any `mapstructure:"memory"`
	ExtraMemory    any `mapstructure:"extraMemory"`
	MinClusterSize any `mapstructure:"minClusterSize"`
	PollPeriod     any `mapstructure:"pollPeriod"`
	Threshold      any `mapstructure:"threshold"`
}

func (v *MetricsServer3122Values_AddonResizer_Nanny) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_AddonResizer struct {
	Enabled         any                                                  `mapstructure:"enabled"`
	Image           MetricsServer3122Values_AddonResizer_Image           `mapstructure:"image"`
	SecurityContext MetricsServer3122Values_AddonResizer_SecurityContext `mapstructure:"securityContext"`
	Resources       MetricsServer3122Values_AddonResizer_Resources       `mapstructure:"resources"`
	Nanny           MetricsServer3122Values_AddonResizer_Nanny           `mapstructure:"nanny"`
}

func (v *MetricsServer3122Values_AddonResizer) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_Metrics struct {
	Enabled any `mapstructure:"enabled"`
}

func (v *MetricsServer3122Values_Metrics) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_ServiceMonitor struct {
	Enabled           any   `mapstructure:"enabled"`
	AdditionalLabels  any   `mapstructure:"additionalLabels"`
	Interval          any   `mapstructure:"interval"`
	ScrapeTimeout     any   `mapstructure:"scrapeTimeout"`
	MetricRelabelings []any `mapstructure:"metricRelabelings"`
	Relabelings       []any `mapstructure:"relabelings"`
}

func (v *MetricsServer3122Values_ServiceMonitor) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// limits:
// cpu:
// memory:
type MetricsServer3122Values_Resources_Requests struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *MetricsServer3122Values_Resources_Requests) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// See https://github.com/kubernetes-sigs/metrics-server#scaling
type MetricsServer3122Values_Resources struct {
	// limits:
	// cpu:
	// memory:
	Requests MetricsServer3122Values_Resources_Requests `mapstructure:"requests"`
}

func (v *MetricsServer3122Values_Resources) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type MetricsServer3122Values_TmpVolume struct {
	EmptyDir any `mapstructure:"emptyDir"`
}

func (v *MetricsServer3122Values_TmpVolume) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// MetricsServer3122Values represents the values of the metrics-server-3.12.2_values.yaml chart
type MetricsServer3122Values struct {
	Image MetricsServer3122Values_Image `mapstructure:"image"`
	// - name: registrySecretName
	ImagePullSecrets     []any                                   `mapstructure:"imagePullSecrets"`
	NameOverride         any                                     `mapstructure:"nameOverride"`
	FullnameOverride     any                                     `mapstructure:"fullnameOverride"`
	ServiceAccount       MetricsServer3122Values_ServiceAccount  `mapstructure:"serviceAccount"`
	Rbac                 MetricsServer3122Values_Rbac            `mapstructure:"rbac"`
	ApiService           MetricsServer3122Values_ApiService      `mapstructure:"apiService"`
	CommonLabels         any                                     `mapstructure:"commonLabels"`
	PodLabels            any                                     `mapstructure:"podLabels"`
	PodAnnotations       any                                     `mapstructure:"podAnnotations"`
	PodSecurityContext   any                                     `mapstructure:"podSecurityContext"`
	SecurityContext      MetricsServer3122Values_SecurityContext `mapstructure:"securityContext"`
	PriorityClassName    any                                     `mapstructure:"priorityClassName"`
	ContainerPort        any                                     `mapstructure:"containerPort"`
	HostNetwork          MetricsServer3122Values_HostNetwork     `mapstructure:"hostNetwork"`
	Replicas             any                                     `mapstructure:"replicas"`
	RevisionHistoryLimit any                                     `mapstructure:"revisionHistoryLimit"`
	// type: RollingUpdate
	// rollingUpdate:
	// maxSurge: 0
	// maxUnavailable: 1
	UpdateStrategy      any                                         `mapstructure:"updateStrategy"`
	PodDisruptionBudget MetricsServer3122Values_PodDisruptionBudget `mapstructure:"podDisruptionBudget"`
	// - --cert-dir=/tmp
	// - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
	// - --kubelet-use-node-status-port
	// - --metric-resolution=15s
	DefaultArgs    []any                                  `mapstructure:"defaultArgs"`
	Args           []any                                  `mapstructure:"args"`
	LivenessProbe  MetricsServer3122Values_LivenessProbe  `mapstructure:"livenessProbe"`
	ReadinessProbe MetricsServer3122Values_ReadinessProbe `mapstructure:"readinessProbe"`
	Service        MetricsServer3122Values_Service        `mapstructure:"service"`
	AddonResizer   MetricsServer3122Values_AddonResizer   `mapstructure:"addonResizer"`
	Metrics        MetricsServer3122Values_Metrics        `mapstructure:"metrics"`
	ServiceMonitor MetricsServer3122Values_ServiceMonitor `mapstructure:"serviceMonitor"`
	// See https://github.com/kubernetes-sigs/metrics-server#scaling
	Resources                 MetricsServer3122Values_Resources `mapstructure:"resources"`
	ExtraVolumeMounts         []any                             `mapstructure:"extraVolumeMounts"`
	ExtraVolumes              []any                             `mapstructure:"extraVolumes"`
	NodeSelector              any                               `mapstructure:"nodeSelector"`
	Tolerations               []any                             `mapstructure:"tolerations"`
	Affinity                  any                               `mapstructure:"affinity"`
	TopologySpreadConstraints []any                             `mapstructure:"topologySpreadConstraints"`
	DnsConfig                 any                               `mapstructure:"dnsConfig"`
	// Annotations to add to the deployment
	DeploymentAnnotations any                               `mapstructure:"deploymentAnnotations"`
	SchedulerName         any                               `mapstructure:"schedulerName"`
	TmpVolume             MetricsServer3122Values_TmpVolume `mapstructure:"tmpVolume"`
}

func (v *MetricsServer3122Values) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}
