// Code generated by CHART_VALUES_STRUCT_GENERATOR. DO NOT EDIT.

// This file was autogenerated by the CHART_VALUES_STRUCT_GENERATOR tool on 2024-12-12.
// Any changes will be overwritten.

// These files are generated from the values.yaml files in the k8s/manifests/charts directory.
// Head to the k8s/manifests/charts/Makefile to see how to generate these files.

// Package values contains the Go structs representing the values of the Helm chart.
package values

import (
	"fmt"
	"github.com/mitchellh/mapstructure"
)

type RawfileCsi090Values_Defaults_Image struct {
	Repository any `mapstructure:"repository"`
	Tag        any `mapstructure:"tag"`
	PullPolicy any `mapstructure:"pullPolicy"`
}

func (v *RawfileCsi090Values_Defaults_Image) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Defaults_Resources_Limits struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *RawfileCsi090Values_Defaults_Resources_Limits) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Defaults_Resources_Requests struct {
	Cpu    any `mapstructure:"cpu"`
	Memory any `mapstructure:"memory"`
}

func (v *RawfileCsi090Values_Defaults_Resources_Requests) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Defaults_Resources struct {
	Limits   RawfileCsi090Values_Defaults_Resources_Limits   `mapstructure:"limits"`
	Requests RawfileCsi090Values_Defaults_Resources_Requests `mapstructure:"requests"`
}

func (v *RawfileCsi090Values_Defaults_Resources) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Defaults struct {
	Image     RawfileCsi090Values_Defaults_Image     `mapstructure:"image"`
	Resources RawfileCsi090Values_Defaults_Resources `mapstructure:"resources"`
}

func (v *RawfileCsi090Values_Defaults) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Controller struct {
	// - csi-driver
	// - --disable-metrics
	CsiDriverArgs []any `mapstructure:"csiDriverArgs"`
}

func (v *RawfileCsi090Values_Controller) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Images struct {
	CsiNodeDriverRegistrar any `mapstructure:"csiNodeDriverRegistrar"`
	CsiProvisioner         any `mapstructure:"csiProvisioner"`
	CsiResizer             any `mapstructure:"csiResizer"`
	CsiSnapshotter         any `mapstructure:"csiSnapshotter"`
}

func (v *RawfileCsi090Values_Images) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Node_Storage struct {
	Path any `mapstructure:"path"`
}

func (v *RawfileCsi090Values_Node_Storage) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Node_Metrics struct {
	Enabled any `mapstructure:"enabled"`
}

func (v *RawfileCsi090Values_Node_Metrics) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_Node struct {
	Storage RawfileCsi090Values_Node_Storage `mapstructure:"storage"`
	Metrics RawfileCsi090Values_Node_Metrics `mapstructure:"metrics"`
}

func (v *RawfileCsi090Values_Node) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_StorageClass struct {
	Enabled           any `mapstructure:"enabled"`
	Name              any `mapstructure:"name"`
	IsDefault         any `mapstructure:"isDefault"`
	ReclaimPolicy     any `mapstructure:"reclaimPolicy"`
	VolumeBindingMode any `mapstructure:"volumeBindingMode"`
}

func (v *RawfileCsi090Values_StorageClass) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

type RawfileCsi090Values_ServiceMonitor struct {
	Enabled  any `mapstructure:"enabled"`
	Interval any `mapstructure:"interval"`
}

func (v *RawfileCsi090Values_ServiceMonitor) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}

// RawfileCsi090Values represents the values of the rawfile-csi-0.9.0_values.yaml chart
type RawfileCsi090Values struct {
	ProvisionerName  any                                `mapstructure:"provisionerName"`
	Defaults         RawfileCsi090Values_Defaults       `mapstructure:"defaults"`
	Controller       RawfileCsi090Values_Controller     `mapstructure:"controller"`
	Images           RawfileCsi090Values_Images         `mapstructure:"images"`
	Node             RawfileCsi090Values_Node           `mapstructure:"node"`
	StorageClass     RawfileCsi090Values_StorageClass   `mapstructure:"storageClass"`
	ImagePullSecrets []any                              `mapstructure:"imagePullSecrets"`
	ServiceMonitor   RawfileCsi090Values_ServiceMonitor `mapstructure:"serviceMonitor"`
}

func (v *RawfileCsi090Values) ToMap() (map[string]any, error) {
	var result map[string]any
	err := mapstructure.Decode(v, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to decode to map[string]any: %w", err)
	}
	return result, nil
}
