// Code generated by CHART_VALUES_STRUCT_GENERATOR. DO NOT EDIT.

// This file was autogenerated by the CHART_VALUES_STRUCT_GENERATOR tool on 2024-12-12.
// Any changes will be overwritten.

// Package values contains the Go structs representing the values of the Helm chart.
package values

func ToAnyList[T any](l []T) []any {
	out := make([]any, len(l))
	for i, v := range l {
		out[i] = v
	}
	return out
}
