name: Bug Report
description: Something is not working

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please fill in the template below
        information about the bug you encountered.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please explain the bug in a few short sentences.
      placeholder: Detail the bug here...
    validations:
      required: true

  - type: textarea
    id: what-should-happen
    attributes:
      label: What Should Happen Instead?
      description: Please explain what the expected behavior is.
      placeholder: Explain the expected outcome...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Are you able to consistently reproduce the issue? Please add a list of steps that lead to the bug.
      placeholder: "1.\n2.\n"
    validations:
      required: true

  - type: textarea
    id: system-information
    attributes:
      label: System information
      description: Please attach the tarball generated by running sudo /snap/k8s/current/k8s/scripts/inspect.sh
      placeholder: Attach your system info tarball...
    validations:
      required: true

  - type: textarea
    id: suggest-fix
    attributes:
      label: Can you suggest a fix?
      description: How do you propose that the issue be fixed?
      placeholder: Suggest a fix if you have one...

  - type: textarea
    id: contribute-fix
    attributes:
      label: Are you interested in contributing with a fix?
      description: yes/no, or @mention maintainers. Community contributions are welcome.
      placeholder: Are you willing to contribute a fix?

  - type: markdown
    attributes:
      value: Thank you for making the k8s-snap better

