name: Download k8s-snap

inputs:
  # Download k8s-snap using either a GH action artifact or a snap channel.
  artifact:
    description: The name of a GH action artifact.
    type: string
  channel:
    description: k8s snap channel.
    type: string
  output-file:
    description: The *.snap destination path.
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Exit if no input provided
      if: ${{ inputs.artifact }} == '' && ${{ inputs.channel }} == ''
      run: |
        echo "No k8s-snap artifact or channel specified..."
        exit 1
    - name: Exit if multiple inputs provided
      if: ${{ inputs.artifact }} != '' && ${{ inputs.channel }} != ''
      run: |
        echo "Received snap artifact AND snap channel."
        exit 1
    - name: Create destination dir.
      run: mkdir -p $(dirname ${{ inputs.output-file }})

    - name: Download snap artifact
      if: ${{ inputs.artifact }} != ''
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: ${{ github.workspace }}
    - name: Move snap artifact.
      if: ${{ inputs.artifact }} != ''
      run: mv ${{ github.workspace }}/${{ inputs.artifact }} ${{ inputs.output-file }}

    - name: Download snap channel
      if: ${{ inputs.artifact }} != ''
      run: |
        cd $(dirname ${{ inputs.output-file }})
        snap download k8s --channel=${{ inputs.channel }} --basename k8s
        mv k8s.snap ${{ inputs.output-file }}
