package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/iancoleman/strcase"
	"gopkg.in/yaml.v3"
)

const (
	toolName = "CHART_VALUES_STRUCT_GENERATOR"
)

type structMeta struct {
	name      string
	docString string
	// inner can be either a fieldMeta or a structMeta
	fields []*fieldMeta
}

type fieldMeta struct {
	name             string
	originalYamlName string
	docString        string
	typ              string
}

type goRecipe struct {
	pkgName string
	structs []*structMeta
}

// fill recursively generates Go recipe definitions from a YAML Node
func (recipe *goRecipe) fill(structName string, node *yaml.Node, docString string) {
	stMeta := &structMeta{
		name:      structName,
		docString: docString,
	}

	for i := 0; i < len(node.Content); i += 2 {
		keyNode := node.Content[i]
		valueNode := node.Content[i+1]
		fieldName := strcase.ToCamel(keyNode.Value)

		field := &fieldMeta{
			name:             fieldName,
			originalYamlName: keyNode.Value,
			docString:        strings.Join(extractComments(keyNode), "\n"),
		}

		supportingComments := []string{}

		// TODO: handle such cases:
		// controller:
		// 	<<: *defaults

		switch valueNode.Kind {
		case yaml.MappingNode:
			// Nested struct
			if len(valueNode.Content) == 0 {
				// place holder, should be repsesented as any to
				// prevent creation of a struct with no fields
				field.typ = "any"
			} else {
				nestedStructName := structName + "_" + fieldName
				field.typ = nestedStructName
				recipe.fill(nestedStructName, valueNode, field.docString)
			}
		case yaml.SequenceNode:
			if len(valueNode.Content) == 0 || len(valueNode.Content[0].Content) == 0 {
				field.typ = "[]any"

				// if list has items, include them as comment
				if len(valueNode.Content) > 0 {
					for _, c := range valueNode.Content {
						supportingComments = append(supportingComments, extractComments(c)...)
						supportingComments = append(supportingComments, fmt.Sprintf("// - %s", c.Value))
					}
				}
			} else {
				// List with its own struct
				nestedListName := structName + "_" + fieldName + "Item"
				field.typ = "[]" + nestedListName

				recipe.fill(nestedListName, valueNode.Content[0], field.docString)
			}
		case yaml.ScalarNode:
			// Scalar value
			field.typ = "any"
		}

		if len(supportingComments) > 0 {
			supDocString := strings.Join(supportingComments, "\n")
			if field.docString != "" {
				field.docString = fmt.Sprintf("%s\n%s", field.docString, supDocString)
			} else {
				field.docString = supDocString
			}
		}
		stMeta.fields = append(stMeta.fields, field)
	}

	recipe.structs = append(recipe.structs, stMeta)
}

// extractComments extracts comments from a YAML node
func extractComments(n *yaml.Node) []string {
	totalLines := []string{}
	if hc := n.HeadComment; hc != "" {
		lines := strings.Split(hc, "\n")
		for _, l := range lines {
			l = strings.TrimSpace(l)
			l = strings.TrimLeft(l, "#")
			l = strings.TrimSpace(l)
			totalLines = append(totalLines, fmt.Sprintf("// %s", l))
		}
	}
	if lc := n.LineComment; lc != "" {
		lines := strings.Split(lc, "\n")
		for _, l := range lines {
			l = strings.TrimSpace(l)
			l = strings.TrimLeft(l, "#")
			l = strings.TrimSpace(l)
			totalLines = append(totalLines, fmt.Sprintf("// %s", l))
		}
	}
	if fc := n.FootComment; fc != "" {
		lines := strings.Split(fc, "\n")
		for _, l := range lines {
			l = strings.TrimSpace(l)
			l = strings.TrimLeft(l, "#")
			l = strings.TrimSpace(l)
			totalLines = append(totalLines, fmt.Sprintf("// %s", l))
		}
	}

	return totalLines
}

func (recipe *goRecipe) generateGoFile() string {
	out := []string{
		fmt.Sprintf(`// Code generated by %[1]s. DO NOT EDIT.

// This file was autogenerated by the %[1]s tool on %[2]s.
// Any changes will be overwritten.

// These files are generated from the values.yaml files in the k8s/manifests/charts directory.
// Head to the k8s/manifests/charts/Makefile to see how to generate these files.

// Package %[3]s contains the Go structs representing the values of the Helm chart.
package %[3]s

import (
	"fmt"
	"github.com/mitchellh/mapstructure"
)
`, toolName, time.Now().Format(time.DateOnly), recipe.pkgName),
	}

	for _, st := range recipe.structs {
		// Add struct docstring
		if st.docString != "" {
			out = append(out, st.docString)
		}

		// Add struct definition
		out = append(out, fmt.Sprintf("type %s struct {", st.name))
		for _, f := range st.fields {
			// TODO: theoretically this should be removed if all cases are handled (e.g. <<: *defaults)
			if f.name == "" || f.typ == "" {
				continue
			}

			if f.docString != "" {
				out = append(out, f.docString)
			}
			out = append(out, fmt.Sprintf("\t%s %s `mapstructure:\"%s\"`", f.name, f.typ, f.originalYamlName))
		}
		out = append(out, "}")

		// Add ToMap() method
		out = append(out, fmt.Sprintf(`
		func (v *%s) ToMap() (map[string]any, error) {
			var result map[string]any
			err := mapstructure.Decode(v, &result)
			if err != nil {
				return nil, fmt.Errorf("failed to decode to map[string]any: %%w", err)
			}
			return result, nil
		}`, st.name))
	}

	return strings.Join(out, "\n")
}

// processYAMLFile reads a YAML file and generates the corresponding .go file
func processYAMLFile(filePath, structName, outputFilePath string, recipe *goRecipe) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("failed to read YAML file %s: %w", filePath, err)
	}

	var rootNode yaml.Node
	if err := yaml.Unmarshal(data, &rootNode); err != nil {
		return fmt.Errorf("failed to parse YAML file %s: %w", filePath, err)
	}

	docString := fmt.Sprintf("// %s represents the values of the %s chart", structName, filePath)
	recipe.fill(structName, rootNode.Content[0], docString)

	if err := os.WriteFile(outputFilePath, []byte(recipe.generateGoFile()), 0644); err != nil {
		return fmt.Errorf("failed to write Go file %s: %w", outputFilePath, err)
	}

	if err := formatGoFile(outputFilePath); err != nil {
		return fmt.Errorf("failed to format Go file %s: %w", outputFilePath, err)
	}

	fmt.Printf("Generated %s\n", outputFilePath)
	return nil
}

// formatGoFile formats a Go file using gofmt
func formatGoFile(filePath string) error {
	if err := runCmd("gofmt", "-w", filePath); err != nil {
		return fmt.Errorf("failed to format %s: %w", filePath, err)
	}
	return nil
}

// runCmd runs a command
func runCmd(parts ...string) error {
	if len(parts) == 0 {
		return fmt.Errorf("no command provided")
	}

	cmd := exec.Command(parts[0], parts[1:]...)
	var out strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to run command: %w\nOutput: %s", err, out.String())
	}

	return nil
}

func main() {
	var (
		sourcesFile string
		pkgName     string
		targetDir   string
	)

	flag.StringVar(&sourcesFile, "sources", "sources.txt", "Path to the file containing the list of YAML sources")
	flag.StringVar(&pkgName, "pkg", "main", "Name of the package to generate")
	flag.StringVar(&targetDir, "dir", ".", "Directory where the generated files will be saved")
	flag.Parse()

	if _, err := os.Stat(targetDir); os.IsNotExist(err) {
		err := os.Mkdir(targetDir, 0755)
		if err != nil {
			log.Fatalf("Failed to create directory: %v\n", err)
		}
	}

	file, err := os.Open(sourcesFile)
	if err != nil {
		log.Fatalf("Failed to open sources file: %v\n", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		yamlFile := scanner.Text()

		if yamlFile == "" {
			// empty line
			continue
		}

		baseName := strings.TrimSuffix(filepath.Base(yamlFile), filepath.Ext(yamlFile))
		structName := strcase.ToCamel(strings.ReplaceAll(strings.ReplaceAll(baseName, ".", "_"), "-", "_"))
		outputFilePath := path.Join(targetDir, fmt.Sprintf("%s.go", baseName))

		recipe := &goRecipe{
			pkgName: pkgName,
		}
		if err := processYAMLFile(yamlFile, structName, outputFilePath, recipe); err != nil {
			log.Fatalf("Error processing file %s: %v\n", yamlFile, err)
		}
	}

	if err := scanner.Err(); err != nil {
		log.Fatalf("Error reading sources file: %v\n", err)
	}

	// generate utils.go file
	utilsFilePath := path.Join(targetDir, "utils.go")
	if err := os.WriteFile(utilsFilePath, []byte(getUtilsContent(pkgName)), 0644); err != nil {
		log.Fatalf("Failed to write Go file %s: %v\n", utilsFilePath, err)
	}
	if err := formatGoFile(utilsFilePath); err != nil {
		log.Fatalf("Failed to format Go file %s: %v\n", utilsFilePath, err)
	}
}

func getUtilsContent(pkgName string) string {
	return fmt.Sprintf(`// Code generated by %[1]s. DO NOT EDIT.

// This file was autogenerated by the %[1]s tool on %[2]s.
// Any changes will be overwritten.

// Package %[3]s contains the Go structs representing the values of the Helm chart.
package %[3]s

func ToAnyList[T any](l []T) []any {
	out := make([]any, len(l))
	for i, v := range l {
		out[i] = v
	}
	return out
}
`,
		toolName, time.Now().Format(time.DateOnly), pkgName,
	)
}
