name: Install lxd

inputs:
  channel:
    description: lxd snap channel.
    type: string
    default: "5.21/stable"

runs:
  using: "composite"
  steps:
    - name: Install lxd snap
      shell: bash
      run: |
        sudo snap refresh lxd --channel ${{ inputs.channel }}
    - name: Initialize lxd
      shell: bash
      run: |
        sudo lxd init --auto
        sudo usermod --append --groups lxd $USER
        sg lxd -c 'lxc version'
    # Docker sets iptables rules that interfere with LXD.
    # https://documentation.ubuntu.com/lxd/en/latest/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-lxd-and-docker
    - name: Apply Docker iptables workaround
      shell: bash
      run: |
        sudo iptables -I DOCKER-USER -i lxdbr0 -j ACCEPT
        sudo iptables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
