{{- if .Values.ipPool.cidrs }}
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: {{ include "ck-loadbalancer.fullname" . }}
  labels:
    {{- include "ck-loadbalancer.labels" . | nindent 4 }}
spec:
  {{- with .Values.ipPool.cidrs }}
  blocks:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
