@startuml
set separator none
title Juju - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Administrator, "Administrator", $descr="", $tags="", $link="")

System_Boundary("Charm_boundary", "Charm", $tags="") {
  Container(Juju.K8s, "K8s", $techn="Charmed Operator", $descr="K8s Charm", $tags="", $link="")
  Container(Juju.K8sWorker, "K8s Worker", $techn="Charmed Operator", $descr="K8s Worker Charm", $tags="", $link="")
  Container(Juju.ApiManager, "K8sd API Manager", $techn="Python", $descr="API Call to K8s", $tags="", $link="")
  Container(Juju.RelationData, "Relation Databags for K8s and K8s worker", $techn="Juju Relation Databag", $descr="", $tags="", $link="")
}

System_Boundary("Juju_boundary", "Juju", $tags="") {
  Container(Juju.JujuController, "Juju Controller", $techn="Snap Package", $descr="", $tags="", $link="")
  Container(Juju.JujuClient, "Juju Client", $techn="Snap Package", $descr="", $tags="", $link="")
}

System_Boundary("K8s_snap", "K8s Snap", $tags="") {
  Container(K8sSnap.K8sd, "K8sd", $techn="Snap Package", $descr="K8s Snap daemon", $tags="", $link="")
}

Rel(Juju.K8s, Juju.ApiManager, "Uses", $techn="", $tags="", $link="")
Rel(Juju.K8sWorker, Juju.ApiManager, "Uses", $techn="", $tags="", $link="")
BiRel(Juju.K8sWorker, Juju.RelationData, "Reads from and writes to", $techn="", $tags="", $link="")
BiRel(Juju.K8s, Juju.RelationData, "Reads from and writes to", $techn="", $tags="", $link="")
Rel(Juju.JujuController, Juju.K8s, "Manages", $techn="", $tags="", $link="")
Rel(Juju.JujuController, Juju.K8sWorker, "Manages", $techn="", $tags="", $link="")
Rel(Administrator, Juju.JujuClient, "Uses", $techn="", $tags="", $link="")
Rel(Juju.JujuClient, Juju.JujuController, "Manages", $techn="", $tags="", $link="")
Rel(Juju.ApiManager, K8sSnap.K8sd, "Manages", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml
