apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ipv6
spec:
  selector:
    matchLabels:
      run: nginx-ipv6
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-ipv6
    spec:
      containers:
      - name: nginx-ipv6
        image: rocks.canonical.com/cdk/diverdane/nginxipv6:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ipv6
  labels:
    run: nginx-ipv6
spec:
  type: NodePort
  ipFamilies:
  - IPv6
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-ipv6
