@startuml
set separator none
title K8s Snap Context View

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(K8sAdmin, "K8s Admin", $descr="Responsible for the K8s cluster, has elevated permissions", $tags="", $link="")
Person(K8sUser, "K8s User", $descr="Interact with the workloads hosted in K8s", $tags="", $link="")
System(CharmK8s, "Charm K8s", $descr="Orchestrating the lifecycle management of K8s", $tags="", $link="")
System(Externaldatastore, "External datastore", $descr="etcd", $tags="", $link="")

System_Boundary("K8sSnapDistribution_boundary", "K8s Snap Distribution", $tags="") {
  Container(K8sSnapDistribution.KubernetesCoreComponents, "Kubernetes Core Components", $techn="", $descr="API server, kubelet, kube-proxy, scheduler, kube-controller", $tags="", $link="")
  Container(K8sSnapDistribution.ContainerRuntime, "Container Runtime", $techn="", $descr="Containerd", $tags="", $link="")
  Container(K8sSnapDistribution.K8sd, "K8sd", $techn="", $descr="Daemon implementing the features available in the k8s snap", $tags="", $link="")
  Container(K8sSnapDistribution.K8sddatastore, "Cluster Datastore", $techn="", $descr="Uses dqlite to store cluster configuration", $tags="", $link="")
  Container(K8sSnapDistribution.Kubectl, "Kubectl", $techn="", $descr="kubectl client for accessing the cluster", $tags="", $link="")
  Container(K8sSnapDistribution.Kubernetesdatastore, "Kubernetes Datastore", $techn="", $descr="Uses etcd to store cluster data", $tags="", $link="")
}

Rel(K8sAdmin, K8sSnapDistribution.K8sd, "Sets up and configures the cluster", $techn="", $tags="", $link="")
Rel(K8sAdmin, K8sSnapDistribution.Kubectl, "Uses to manage the cluster", $techn="", $tags="", $link="")
Rel(K8sUser, K8sSnapDistribution.Kubectl, "Interacts with workloads hosted in K8s", $techn="", $tags="", $link="")
Rel(CharmK8s, K8sSnapDistribution.K8sd, "Orchestrates the lifecycle management of K8s", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution.K8sd, K8sSnapDistribution.K8sddatastore, "Stores data in", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution.KubernetesCoreComponents, K8sSnapDistribution.Kubernetesdatastore, "Stores data in", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution.Kubernetesdatastore, Externaldatastore, "May be replaced by", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution.K8sd, K8sSnapDistribution.KubernetesCoreComponents, "Configures", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution.KubernetesCoreComponents, K8sSnapDistribution.ContainerRuntime, "Uses", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution.Kubectl, K8sSnapDistribution.KubernetesCoreComponents, "Sends API requests", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution.K8sd, K8sSnapDistribution.ContainerRuntime, "Configures", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml
