{{- if and (eq .Values.driver "metallb") .Values.bgp.enabled }}
{{- range .Values.bgp.bfdProfiles }}
---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ck-loadbalancer.labels" $ | nindent 4 }}
spec:
  {{- if .receiveInterval }}
  receiveInterval: {{ .receiveInterval }}
  {{- end }}
  {{- if .transmitInterval }}
  transmitInterval: {{ .transmitInterval }}
  {{- end }}
  {{- if .detectMultiplier }}
  detectMultiplier: {{ .detectMultiplier }}
  {{- end }}
  {{- if .echoInterval }}
  echoInterval: {{ .echoInterval }}
  {{- end }}
  {{- if .echoMode }}
  echoMode: {{ .echoMode }}
  {{- end }}
  {{- if .passiveMode }}
  passiveMode: {{ .passiveMode }}
  {{- end }}
  {{- if .minimumTtl }}
  minimumTtl: {{ .minimumTtl }}
  {{- end }}
{{- end }}
{{- end }}
