@startuml
set separator none
title System Landscape

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

Person(K8sAdmin, "K8s Admin", $descr="", $tags="", $link="")
Person(K8sUser, "K8s User", $descr="", $tags="", $link="")
System(CharmK8s, "Charm K8s", $descr="", $tags="", $link="")
System(LoadBalancer, "Load Balancer", $descr="External LB, offered by the substrate (cloud). Could be replaced by any alternative solution.", $tags="", $link="")
System(Storage, "Storage", $descr="External storage, offered by the substrate (cloud). Could be replaced by any storage solution.", $tags="", $link="")
System(IdentityManagementSystem, "Identity Management System", $descr="The external identity system, offered by the substrate (cloud). Could be replaced by any alternative system.", $tags="", $link="")
System(Externaldatastore, "External datastore", $descr="etcd", $tags="", $link="")
System(K8sSnapDistribution, "K8s Snap Distribution", $descr="The Kubernetes distribution in a snap", $tags="", $link="")

Rel(K8sAdmin, K8sSnapDistribution, "Sets up and configures the cluster", $techn="", $tags="", $link="")
Rel(K8sAdmin, CharmK8s, "Manages cluster's lifecycle", $techn="", $tags="", $link="")
Rel(K8sUser, K8sSnapDistribution, "Interacts with workloads hosted in K8s", $techn="", $tags="", $link="")
Rel(CharmK8s, K8sSnapDistribution, "Orchestrates the lifecycle management of K8s", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution, Storage, "Hosted workloads use storage", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution, IdentityManagementSystem, "Retrieves users identity", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution, Externaldatastore, "Stores cluster data", $techn="", $tags="", $link="")
Rel(K8sSnapDistribution, LoadBalancer, "Routes client requests", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml
