---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contour-gateway-provisioner
  namespace: projectcontour
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
