name: k8s
adopt-info: kubernetes-version
summary: Canonical Kubernetes, a CNCF-conformant K8s distribution by Canonical
description: |-
  Canonical Kubernetes is an opinionated and CNCF conformant Kubernetes delivered by snaps.
  Enjoy the simplified, almost zero, operations and enhanced security posture
  on any infrastructure
license: GPL-3.0
grade: stable
confinement: classic
# Note(ben): Snapcraft does not expose its base for part builds, so we need to set it manually.
# Feature request tracked in https://github.com/canonical/snapcraft/issues/5614
# For now, remember to also update OPENSSL_MODULES and etcd part BASE when bumping this version.
base: core22
environment:
  REAL_PATH: $PATH
  REAL_LD_LIBRARY_PATH: $LD_LIBRARY_PATH
  CRAFT_ARCH_TRIPLET_BUILD_FOR: $CRAFT_ARCH_TRIPLET_BUILD_FOR
  # Note(ben): Needs to be changed to /snap/core24/current/usr/lib/x86_64-linux-gnu/ossl-modules/
  # when base is updated to core24 (mind the removed "-3").
  OPENSSL_MODULES: /snap/core22/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ossl-modules-3/

architectures:
  - build-on: [amd64]
  - build-on: [arm64]
  - build-on: [ppc64el]
  - build-on: [s390x]

parts:
  build-deps:
    plugin: nil
    build-snaps:
      - go/1.25-fips/stable
    build-attributes: [enable-patchelf]
    build-packages:
      - sudo
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - bison
      - btrfs-progs
      - libbtrfs-dev
      - build-essential
      - curl
      - flex
      - git
      - libjansson-dev
      - liblz4-dev
      - libnetfilter-conntrack-dev
      - libnetfilter-conntrack3
      - libnfnetlink-dev
      - libseccomp-dev
      - libtool
      - libssl-dev
      - patchelf
      - pkg-config
      - rsync
      - tcl
      - python3-pip

  etcd:
    plugin: nil
    after: [build-deps]
    source: build-scripts/components/etcd
    build-environment:
    - BASE: core22  # Note: This field must match the base field above.
    - BIN: $CRAFT_STAGE/bin/etcd
    override-build: $CRAFT_PROJECT_DIR/build-scripts/build-component.sh etcd
    build-attributes: [enable-patchelf]
    override-prime: |-
      case "$CRAFT_ARCH_TRIPLET_BUILD_FOR" in
        x86_64-linux-gnu|aarch64-linux-gnu)
          $CRAFT_PROJECT_DIR/build-scripts/hack/patch-elf-with-lief.sh \
            $BASE $BIN $CRAFT_ARCH_TRIPLET_BUILD_FOR
          ;;
        *)
          # Only amd64/arm64 can use the LIEF-patcher python script above.
          # Fallback intentionally to snapcraft's patchelf on other architectures.
          echo "==> Applying Snap-native patchelf"
          craftctl default
          ;;
      esac

  k8sd:
    source: build-scripts/components/k8sd
    build-attributes: [enable-patchelf]
    plugin: nil
    override-build: $CRAFT_PROJECT_DIR/build-scripts/build-component.sh k8sd

  cni:
    after: [build-deps]
    plugin: nil
    source: build-scripts/components/cni
    build-attributes: [enable-patchelf]
    override-build: $CRAFT_PROJECT_DIR/build-scripts/build-component.sh cni

  kubernetes:
    after: [build-deps]
    plugin: nil
    source: build-scripts
    build-attributes: [enable-patchelf]
    override-build: $CRAFT_PROJECT_DIR/build-scripts/build-component.sh kubernetes

  kubernetes-version:
    plugin: nil
    source: build-scripts/components/kubernetes
    override-build: craftctl set version="$(cat ./version)"

  helm:
    after: [build-deps]
    build-attributes: [enable-patchelf]
    plugin: nil
    source: build-scripts/components/helm
    override-build: $CRAFT_PROJECT_DIR/build-scripts/build-component.sh helm

  libmnl:
    after: [build-deps]
    plugin: autotools
    source: https://www.netfilter.org/pub/libmnl/libmnl-1.0.4.tar.bz2
    build-attributes: [enable-patchelf]
    prime:
      - -usr/local/include

  libnftnl:
    after: [libmnl]
    plugin: autotools
    source: https://www.netfilter.org/projects/libnftnl/files/libnftnl-1.1.8.tar.bz2
    build-attributes: [enable-patchelf]
    build-environment:
      - LIBMNL_LIBS: $CRAFT_STAGE/usr/lib
    prime:
      - -usr/local/include

  iptables:
    after: [libnftnl]
    source: https://www.netfilter.org/projects/iptables/files/iptables-1.8.6.tar.bz2
    plugin: autotools
    build-attributes: [enable-patchelf]
    build-environment:
      - LIBMNL_LIBS: $CRAFT_STAGE/usr/lib
      - LIBNFTNL_LIBS: $CRAFT_STAGE/usr/lib
    autotools-configure-parameters:
      - "--prefix=/usr"
      - "--exec-prefix=/"
      - "--disable-shared"
      - "--enable-static"
    stage:
      - -usr
      - -lib/pkgconfig
      - -bin/iptables-xml

  containerd:
    after: [runc]
    plugin: nil
    source: build-scripts/components/containerd
    override-build: $CRAFT_PROJECT_DIR/build-scripts/build-component.sh containerd
    build-environment:
    - BASE: core22  # Note: This field must match the base field above.
    build-attributes: [enable-patchelf]
    override-prime: |-
      case "$CRAFT_ARCH_TRIPLET_BUILD_FOR" in
        x86_64-linux-gnu|aarch64-linux-gnu)
          for BIN in containerd ctr containerd-shim-runc-v2; do
            $CRAFT_PROJECT_DIR/build-scripts/hack/patch-elf-with-lief.sh \
                $BASE $CRAFT_STAGE/bin/$BIN $CRAFT_ARCH_TRIPLET_BUILD_FOR
          done
          ;;
        *)
          # Only amd64/arm64 can use the LIEF-patcher python script above.
          # Fallback intentionally to snapcraft's patchelf on other architectures.
          echo "==> Applying Snap-native patchelf"
          craftctl default
          ;;
      esac

  runc:
    after: [iptables, build-deps]
    plugin: nil
    build-attributes: [enable-patchelf]
    source: build-scripts/components/runc
    override-build: $CRAFT_PROJECT_DIR/build-scripts/build-component.sh runc

  bash-utils:
    plugin: nil
    build-attributes: [enable-patchelf]
    stage-packages:
      - conntrack
      - coreutils
      - diffutils
      - erofs-utils
      - ethtool
      - hostname
      - iproute2
      - ipset
      - kmod
      - libatm1
      - libnss-resolve
      - libnss-myhostname
      - libnss-mymachines
      - members
      - nano
      - net-tools
      - openssl
      - procps
      - tar
      - util-linux
    stage:
      - -etc/bash_completion.d
      - -etc/cron.d
      - -etc/depmod.d
      - -etc/ldap
      - -etc/logrotate.d
      - -etc/init.d
      - -etc/perl
      - -etc/rsyslog.d
      - -etc/sudoers.d
      - -lib/systemd
      - -usr/bin/perl*
      - -usr/include
      - -usr/lib/*/*perl*
      - -usr/share

  k8s:
    plugin: nil
    source: k8s
    build-attributes: [enable-patchelf]
    override-build: |
      rm $CRAFT_PART_INSTALL/k8s -rf
      cp --archive --link --no-dereference . $CRAFT_PART_INSTALL/k8s

  bom:
    after:
      - cni
      - containerd
      - etcd
      - helm
      - k8sd
      - kubernetes
      - runc
    plugin: nil
    source: .
    build-packages:
      - python3-yaml
    override-build: |
      ./build-scripts/generate-bom.py > "${CRAFT_PART_INSTALL}/bom.json"

  resources:
    plugin: dump
    source: k8s/resources
    source-type: local
    organize:
      "*": etc/
    stage:
      - etc/

apps:
  k8s:
    command: k8s/wrappers/commands/k8s
  containerd:
    command: k8s/wrappers/services/containerd
    daemon: notify
    install-mode: disable
    # when stopped send only sigterm
    # https://forum.snapcraft.io/t/process-lifecycle-on-snap-refresh/140/37
    stop-mode: sigterm
    restart-condition: always
    start-timeout: 5m
    before: [kubelet]
  etcd:
    command: k8s/wrappers/services/etcd
    install-mode: disable
    daemon: simple
    before: [kube-apiserver]
  k8sd:
    command: k8s/wrappers/services/k8sd
    install-mode: enable
    daemon: simple
  kubelet:
    install-mode: disable
    command: k8s/wrappers/services/kubelet
    daemon: simple
    after: [containerd]
  kube-apiserver:
    install-mode: disable
    command: k8s/wrappers/services/kube-apiserver
    daemon: simple
    before: [kubelet, kube-controller-manager, kube-proxy, kube-scheduler]
    stop-timeout: 5s
  kube-controller-manager:
    install-mode: disable
    command: k8s/wrappers/services/kube-controller-manager
    daemon: simple
    after: [kube-apiserver]
  kube-proxy:
    install-mode: disable
    command: k8s/wrappers/services/kube-proxy
    daemon: simple
    after: [kube-apiserver]
  kube-scheduler:
    install-mode: disable
    command: k8s/wrappers/services/kube-scheduler
    daemon: simple
    after: [kube-apiserver]
  k8s-apiserver-proxy:
    install-mode: disable
    command: k8s/wrappers/services/k8s-apiserver-proxy
    daemon: simple
    before: [kubelet, kube-proxy]
