name: k8s
adopt-info: kubernetes-version
summary: Canonical Kubernetes, a CNCF-conformant K8s distribution by Canonical
description: |-
  Canonical Kubernetes is an opinionated and CNCF conformant Kubernetes delivered by snaps.
  Enjoy the simplified, almost zero, operations and enhanced security posture
  on any infrastructure
license: GPL-3.0
grade: stable
confinement: classic
base: core20
environment:
  REAL_PATH: $PATH
  REAL_LD_LIBRARY_PATH: $LD_LIBRARY_PATH
  SNAPCRAFT_ARCH_TRIPLET: $SNAPCRAFT_ARCH_TRIPLET

architectures:
  - amd64
  - arm64

parts:
  build-deps:
    plugin: nil
    build-snaps:
      - go/1.21/stable
    build-packages:
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - bison
      - btrfs-progs
      - libbtrfs-dev
      - build-essential
      - curl
      - flex
      - git
      - libjansson-dev
      - liblz4-dev
      - libnetfilter-conntrack-dev
      - libnetfilter-conntrack3
      - libnfnetlink-dev
      - libseccomp-dev
      - libtool
      - pkg-config
      - rsync
      - tcl

  dqlite:
    after: [build-deps]
    plugin: nil
    source: src/k8s/hack
    override-prime: ""
    override-build: |
      DQLITE_STAGING_DIR="${SNAPCRAFT_STAGE}/static-dqlite-deps"
      if [ -d "${DQLITE_STAGING_DIR}" ]; then
        rm -rf "${DQLITE_STAGING_DIR}"
      fi
      mkdir "${DQLITE_STAGING_DIR}"
      cp -rv * "${DQLITE_STAGING_DIR}"

      # Build dqlite libraries on the staging area
      "${DQLITE_STAGING_DIR}/static-dqlite.sh"

  k8s-dqlite:
    after: [dqlite]
    plugin: nil
    source: build-scripts
    override-build: ./build-component.sh k8s-dqlite

  k8s-binaries:
    after: [dqlite]
    source: src/k8s
    plugin: nil
    override-build: |
      INSTALL="${SNAPCRAFT_PART_INSTALL}/bin"
      mkdir -p "${INSTALL}"

      export DQLITE_BUILD_SCRIPTS_DIR="${SNAPCRAFT_STAGE}/static-dqlite-deps"
      make static -j

      for binary in k8s k8sd k8s-apiserver-proxy; do
        cp -P "bin/static/${binary}" "${INSTALL}/${binary}"
      done

  cni:
    after: [build-deps]
    plugin: nil
    source: build-scripts
    override-build: ./build-component.sh cni

  kubernetes:
    after: [build-deps]
    plugin: nil
    source: build-scripts
    override-build: ./build-component.sh kubernetes

  kubernetes-version:
    plugin: nil
    source: build-scripts/components/kubernetes
    override-build: snapcraftctl set-version "$(./version.sh)"

  helm:
    after: [build-deps]
    build-attributes: [no-patchelf]
    plugin: nil
    source: build-scripts
    override-build: ./build-component.sh helm

  libmnl:
    after: [build-deps]
    plugin: autotools
    source: https://www.netfilter.org/pub/libmnl/libmnl-1.0.4.tar.bz2
    prime:
      - -usr/local/include

  libnftnl:
    after: [libmnl]
    plugin: autotools
    source: https://www.netfilter.org/projects/libnftnl/files/libnftnl-1.1.8.tar.bz2
    build-environment:
      - LIBMNL_LIBS: $SNAPCRAFT_STAGE/usr/lib
    prime:
      - -usr/local/include

  iptables:
    after: [libnftnl]
    source: https://www.netfilter.org/projects/iptables/files/iptables-1.8.6.tar.bz2
    plugin: autotools
    build-environment:
      - LIBMNL_LIBS: $SNAPCRAFT_STAGE/usr/lib
      - LIBNFTNL_LIBS: $SNAPCRAFT_STAGE/usr/lib
    autotools-configure-parameters:
      - "--prefix=/usr"
      - "--exec-prefix=/"
      - "--disable-shared"
      - "--enable-static"
    stage:
      - -usr
      - -lib/pkgconfig
      - -bin/iptables-xml

  containerd:
    after: [runc]
    plugin: nil
    build-attributes: [no-patchelf]
    source: build-scripts
    override-build: ./build-component.sh containerd

  runc:
    after: [iptables, build-deps]
    plugin: nil
    build-attributes: [no-patchelf]
    source: build-scripts
    override-build: ./build-component.sh runc

  cilium-dbg:
    after: [build-deps]
    plugin: make
    source-type: git
    source: https://github.com/cilium/cilium.git
    source-tag: v1.15.2
    source-depth: 1
    source-subdir: cilium-dbg

  bash-utils:
    plugin: nil
    stage-packages:
      - conntrack
      - coreutils
      - diffutils
      - ethtool
      - hostname
      - iproute2
      - kmod
      - libatm1
      - libnss-resolve
      - libnss-myhostname
      - libnss-mymachines
      - members
      - nano
      - net-tools
      - openssl
      - procps
      - tar
      - util-linux
    stage:
      - -etc/bash_completion.d
      - -etc/cron.d
      - -etc/depmod.d
      - -etc/ldap
      - -etc/logrotate.d
      - -etc/init.d
      - -etc/perl
      - -etc/rsyslog.d
      - -etc/sudoers.d
      - -lib/systemd
      - -usr/bin/perl*
      - -usr/include
      - -usr/lib/*/*perl*
      - -usr/share

  k8s:
    plugin: nil
    source: k8s
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/k8s -rf
      cp --archive --link --no-dereference . $SNAPCRAFT_PART_INSTALL/k8s

  bom:
    after:
      - cni
      - containerd
      - helm
      - k8s-dqlite
      - kubernetes
      - runc
    plugin: nil
    source: .
    build-packages:
      - python3-yaml
    override-build: |
      ./build-scripts/generate-bom.py > "${SNAPCRAFT_PART_INSTALL}/bom.json"

apps:
  k8s:
    command: k8s/wrappers/commands/k8s
  containerd:
    command: k8s/wrappers/services/containerd
    daemon: notify
    install-mode: disable
    # when stopped send only sigterm
    # https://forum.snapcraft.io/t/process-lifecycle-on-snap-refresh/140/37
    stop-mode: sigterm
    restart-condition: always
    start-timeout: 5m
  k8s-dqlite:
    command: k8s/wrappers/services/k8s-dqlite
    install-mode: disable
    daemon: simple
  k8sd:
    command: k8s/wrappers/services/k8sd
    install-mode: enable
    daemon: simple
  kubelet:
    install-mode: disable
    command: k8s/wrappers/services/kubelet
    daemon: simple
  kube-apiserver:
    install-mode: disable
    command: k8s/wrappers/services/kube-apiserver
    daemon: simple
  kube-controller-manager:
    install-mode: disable
    command: k8s/wrappers/services/kube-controller-manager
    daemon: simple
  kube-proxy:
    install-mode: disable
    command: k8s/wrappers/services/kube-proxy
    daemon: simple
  kube-scheduler:
    install-mode: disable
    command: k8s/wrappers/services/kube-scheduler
    daemon: simple
  k8s-apiserver-proxy:
    install-mode: disable
    command: k8s/wrappers/services/k8s-apiserver-proxy
    daemon: simple
