#!/bin/bash -e

. "$SNAP/k8s/lib.sh"

k8s::common::setup_env

# Ensure XDG_RUNTIME_DIR exists, needed by runc for 'kubectl exec' to work
[ ! -z "${XDG_RUNTIME_DIR:=}" ] && mkdir -p "${XDG_RUNTIME_DIR}"

# Apply the containerd profile
k8s::common::is_strict && apparmor_parser -r "$SNAP/k8s/profiles/containerd"

k8s::common::execute_service containerd
