#!/bin/bash -e

. "$SNAP/k8s/lib.sh"

k8s::common::setup_env

k8s::common::is_strict && k8s::kubelet::ensure_shared_root_dir

k8s::util::wait_containerd_socket
k8s::util::wait_kube_apiserver

k8s::common::execute_service kubelet
