apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: upgrades.k8sd.io
spec:
  group: k8sd.io  # API group for the resource
  names:
    kind: Upgrade
    plural: upgrades
    singular: upgrade
  # The Upgrade CRD is only relevant for the internal upgrade controller.
  scope: Cluster
  versions:
    - name: v1alpha
      served: true  # Serve this version in API requests
      storage: true  # Store custom objects in this version
      subresources:
        status: {}  # Allows `status` updates separately
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: "Current upgrade phase."
          jsonPath: ".status.phase"
        - name: UpgradedNodes
          type: array
          items:
            type: string
          description: "Number of nodes that have been upgraded."
          jsonPath: ".status.upgradedNodes"
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                upgradedNodes:
                  description: "List of nodes that have been upgraded."
                  type: array
                  items:
                    type: string
                phase:
                  description: "Current upgrade phase."
                  type: string
                  enum: ["Preparation", "NodeUpgrade", "FeatureUpgrade", "Completed", "Failed"]
