name: Auto-merge Successful PRs

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes

permissions:
  contents: read
  pull-requests: write

jobs:
  find_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY_TO_UPDATE_STRICT_BRANCH }}

        # Fetch open pull requests and check for status checks on automerge PRs
      - name: Auto-merge pull requests if all status checks pass
        run: |
            build-scripts/hack/auto-merge-successful-prs.sh
