name: CNCF Conformance Nightly Latest/Edge Tests

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every monday midnight
  pull_request:
permissions:
  contents: read

jobs:
  test-cncf-conformance:
    name: CNCF Conformance ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.releases }}
    strategy:
      matrix:
        os: ["ubuntu:24.04"]
        arch: ["amd64"]
        releases: ["latest/edge/moonray"] # TODO add latest/edge after upgrade Cilium to 1.17
    runs-on: ${{ matrix.arch == 'arm64' && 'Ubuntu_ARM64_4C_16G_01' || 'ubuntu-20.04' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install tox
        run: pip install tox

      - name: Install lxd
        run: |
          sudo snap refresh lxd --channel 5.21/stable
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
          echo "os_dash=${{ matrix.os }}" | sed 's/:/-/g' >> $GITHUB_ENV

      - name: download ${{ matrix.releases }} k8s snap
        run: |
          snap download k8s --channel=${{ matrix.releases }} --basename k8s

      - name: Run end to end tests
        env:
          TEST_SNAP: ${{ github.workspace }}/k8s.snap
          TEST_SUBSTRATE: lxd
          TEST_LXD_IMAGE: ${{ matrix.os }}
          TEST_CNCF_E2E: true
          TEST_INSPECTION_REPORTS_DIR: ${{ github.workspace }}/inspection-reports
        working-directory: tests/integration
        run: |
          sg lxd -c 'tox -e e2e'

      - name: Extract report
        if: always()
        working-directory: tests/integration
        run: |
          tar -xf sonobuoy_e2e.tar.gz --one-top-level

      - name: Upload inspection report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report_sonobuoy_e2e_${{ github.os_dash }}_${{ matrix.arch }}
          path: tests/integration/sonobuoy_e2e
