name: Integration Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - autoupdate/strict
      - autoupdate/moonray
      - 'release-[0-9]+.[0-9]+'
      - 'autoupdate/release-[0-9]+.[0-9]+-strict'
      - 'autoupdate/sync/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

jobs:
  build-snap:
    name: Build k8s-snap
    uses: ./.github/workflows/build-snap.yaml

  test-branches:
    name: Test Branch Management
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install tox
        run: pip install tox
      - name: Run branch_management tests
        run: |
          tox -c tests/branch_management -e test

  get-e2e-test-tags:
    name: "Get e2e test tags"
    uses: ./.github/workflows/get-e2e-test-tags.yaml

  test-integration:
    name: Test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu:20.04", "ubuntu:22.04", "ubuntu:24.04"]
    needs: [build-snap, get-e2e-test-tags]
    uses: ./.github/workflows/run-e2e-tests.yaml
    with:
      arch: amd64
      os: ${{ matrix.os }}
      test-tags: ${{ needs.get-e2e-test-tags.outputs.test-tags}}
      artifact: ${{ needs.build-snap.outputs.snap-artifact}}

  security-scan:
    name: Security scan
    needs: build-snap
    uses: ./.github/workflows/security-scan.yaml
    with:
      artifact: ${{ needs.build-snap.outputs.snap-artifact}}
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
