name: Informing Integration Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - 'release-[0-9]+.[0-9]+'
      - 'autoupdate/sync/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

jobs:
  build-snap:
    name: Build ${{ matrix.patch }}
    uses: ./.github/workflows/build-snap.yaml
    strategy:
      matrix:
        patch: ["moonray"]
      fail-fast: false
    with:
      flavor: ${{ matrix.patch }}

  get-e2e-test-tags:
    name: "Get e2e test tags"
    uses: ./.github/workflows/get-e2e-test-tags.yaml

  test-integration:
    name: Test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu:20.04"]
        patch: ["moonray"]
    needs: [build-snap, get-e2e-test-tags]
    uses: ./.github/workflows/run-e2e-tests.yaml
    with:
      arch: amd64
      os: ${{ matrix.os }}
      test-tags: ${{ needs.get-e2e-test-tags.outputs.test-tags}}
      artifact: k8s-${{ matrix.patch }}.snap
