name: "Docs: Markdown lint"

on:
  pull_request:
    paths:
      - 'docs/**'
      - '!docs/canonicalk8s/_parts/**'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Create venv
        working-directory: "docs/canonicalk8s"
        run: make install
      - name: Lint markdown
        working-directory: "docs/canonicalk8s"
        run: make lint-md
