name: "Docs: Markdown lint"

on:
  pull_request:
    paths:
      - 'docs/**'
      - '!docs/canonicalk8s/_parts/**'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16
        with:
          config: "docs/canonicalk8s/.sphinx/.markdownlint.json"
          globs: |
            docs/**/*.md
            !docs/canonicalk8s/_parts/**
