name: Integration Tests (Strict)

on:
  push:
    branches:
      - main
      - 'release-[0-9]+.[0-9]+'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            canonical-bos01.cdn.snapcraftcontent.com:443
            canonical-lgw01.cdn.snapcraftcontent.com:443
            cdn03.quay.io:443
            cilium.io:443
            cloud-images.ubuntu.com:443
            cloud-images.ubuntu.com:80
            files.pythonhosted.org:443
            ghcr.io:443
            github.com:443
            images.linuxcontainers.org:443
            k8s.gcr.io:443
            objects.githubusercontent.com:443
            one.one.one.one:443
            one.one.one.one:80
            pkg-containers.githubusercontent.com:443
            prod-registry-k8s-io-us-east-1.s3.dualstack.us-east-1.amazonaws.com:443
            prod-registry-k8s-io-us-east-2.s3.dualstack.us-east-2.amazonaws.com:443
            prod-registry-k8s-io-us-west-1.s3.dualstack.us-west-1.amazonaws.com:443
            production.cloudflare.docker.com:443
            pypi.org:443
            quay.io:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            registry.k8s.io:443
            storage.googleapis.com:443
            us-central1-docker.pkg.dev:443
            us-east4-docker.pkg.dev:443
            us-west2-docker.pkg.dev:443
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Install lxd
        run: |
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Apply strict patch
        run: |
          git config --global user.email k8s-bot@canonical.com
          git config --global user.name k8s-bot
          git am ./build-scripts/patches/strict/*.patch
      - name: Build snap
        run: |
          sg lxd -c 'snapcraft --use-lxd'
          mv k8s_*.snap k8s-strict.snap
      - name: Uploading snap
        uses: actions/upload-artifact@v4
        with:
          name: k8s-strict.snap
          path: k8s-strict.snap

  test-integration:
    needs: [ build ]
    name: Test ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu:20.04"]
    runs-on: ubuntu-20.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install tox
        run: pip install tox
      - name: Install lxd
        run: |
          sudo snap refresh lxd --channel 5.19/stable
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
      - name: Download snap
        uses: actions/download-artifact@v4
        with:
          name: k8s-strict.snap
          path: build
      - name: Run end to end tests
        run: |
          export TEST_SNAP="$PWD/build/k8s-strict.snap"
          export TEST_SUBSTRATE=lxd
          export TEST_LXD_IMAGE=${{ matrix.os }}
          cd tests/integration && sg lxd -c 'tox -e integration'
