name: Integration Tests (Strict)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Install lxd
        run: |
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Apply strict patch
        run: |
          git checkout -b autoupdate/strict
          git config --global user.email k8s-bot@canonical.com
          git config --global user.name k8s-bot
          git am ./build-scripts/patches/strict/*.patch
      - name: Build snap
        run: |
          sg lxd -c 'snapcraft --use-lxd'
          mv k8s_*.snap k8s-strict.snap
      - name: Uploading snap
        uses: actions/upload-artifact@v4
        with:
          name: k8s-strict.snap
          path: k8s-strict.snap

  test-integration:
    name: Test ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu:20.04"]
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install tox
        run: pip install tox
      - name: Install lxd
        run: |
          sudo snap refresh lxd --channel 5.19/stable
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
      - name: Download snap
        uses: actions/download-artifact@v4
        with:
          name: k8s-strict.snap
          path: build
      - name: Run end to end tests
        run: |
          export TEST_SNAP="$PWD/build/k8s-strict.snap"
          export TEST_SUBSTRATE=lxd
          export TEST_LXD_IMAGE=${{ matrix.os }}
          cd tests/integration && sg lxd -c 'tox -e integration'
