on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync registry.k8s.io to ghcr.io/canonical
        env:
          DEST_CREDS: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
        run: |
          ${GITHUB_WORKSPACE}/build-scripts/hack/sync-registry.sh
