name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 6 * * 1" # Every Monday at 06:00 UTC

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files due to `advanced-security:true`
      contents: read # Needed to clone the repo
      actions: read # Needed for upload-sarif to read workflow run info

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          zizmor-args: --pedantic
          advanced-security: "true"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
