name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 6 * * 1" # Every Monday at 06:00 UTC

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files due to `advanced-security:true`
      contents: read # Needed to clone the repo
      actions: read # Needed for upload-sarif to read workflow run info

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          zizmor-args: --pedantic
          advanced-security: "true"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
