#!/bin/bash -xe

DIR="$(realpath "$(dirname "${0}")")"

# Configure git author
git config user.email k8s-bot@canonical.com
git config user.name k8s-bot

# Remove unrelated tests
rm "${DIR}/../../../tests/integration/tests/test_cilium_e2e.py"
## TODO: restore when loadbalancer is implemented
rm "${DIR}/../../../tests/integration/tests/test_loadbalancer.py"

sed -i 's/ingressClassName: cilium/ingressClassName: ck-ingress/g' "${DIR}/../../../tests/integration/templates/ingress-test.yaml"

git commit -a -m "Remove unrelated tests"

# Apply strict patch
git am "${DIR}/0001-Moonray.patch"
