#!/bin/bash -xe

DIR="$(realpath "$(dirname "${0}")")"

# Configure git author if unset
git_email=$(git config --default "" user.email)
if [ -z "${git_email}" ]; then
    git config user.email k8s-team-ci@canonical.com
    git config user.name 'k8s-team-ci (CDK Bot)'
fi

# Remove unrelated tests
rm "${DIR}/../../../tests/integration/tests/test_cilium_e2e.py"

sed -i 's/ingressClassName: cilium/ingressClassName: ck-ingress/g' "${DIR}/../../../tests/integration/templates/ingress-test.yaml"

git commit -a -m "Remove unrelated tests"

# Apply strict patch
git am "${DIR}/0001-Moonray.patch"
