#!/bin/bash -e

. "$SNAP/k8s/lib.sh"

k8s::common::setup_env

# disable snap set/get on startup as k8sd is not up yet.
# the sync will be enabled in the bootstrap hook.
k8s::cmd::k8s x-snapd-config disable

# k8s has a REST interface to initialize a cluster.
# In order to interact with the REST API the k8sd service
# needs to be started and configured in the installation step.
k8s::init::k8sd
