#!/bin/bash -e
. "$SNAP/k8s/lib.sh"

k8s::common::setup_env

# Reject upgrade if deprecated k8s-dqlite datastore is used.
if [ -d "$SNAP_COMMON/var/lib/k8s-dqlite" ]; then
  echo "ERROR: upgrade blocked: k8s-dqlite is no longer supported in version 1.36 and later."
  echo "Either stay on version 1.35 or deploy a new cluster with etcd as the datastore."
  exit 1
fi

# Indicate that an update has been performed.
# Many actions require k8sd to be active which is not
# the case in the snap hook. Hence, we use a lock file
# to indicate that an update has been performed and
# run a custom post-refresh hook in the k8sd service.
mkdir -p "$SNAP_COMMON/lock"
touch "$SNAP_COMMON/lock/post-refresh"
