#!/bin/bash -e
. "$SNAP/k8s/lib.sh"

k8s::common::setup_env

# Indicate that an update has been performed.
# Many actions require k8sd to be active which is not
# the case in the snap hook. Hence, we use a lock file
# to indicate that an update has been performed and
# run a custom post-refresh hook in the k8sd service.
mkdir -p "$SNAP_COMMON/lock"
touch "$SNAP_COMMON/lock/post-refresh"
